### ISSUE TITLE
Not Connecting with some clients

### ISSUE THREAD

**Issue by mohin-xe** [nanomq/nanomq#1056]
Connection not working with some clients like []()https://github.com/marvinroger/async-mqtt-client and other clients downloaded from apple store but same time working with some Android clients

**Comment by JaylinYu** [comment]
Could you please provide any detailed log? from both client and broker side? 

We will try this repo later.

BTW, NanoMQ doesn't support MQTT 3.1

**Comment by mohin-xe** [comment]
> Could you please provide any detailed log? from both client and broker side? 
> 
> We will try this repo later.
> 
> BTW, NanoMQ doesn't support MQTT 3.1

But the website says it supports 3.1.1

**Comment by JaylinYu** [comment]
Yes to 3.1.1, no to 3.1. Plz find difference between 3.1.1 and 3.1 here https://www.oasis-open.org/committees/download.php/55095/mqtt-diffs-v1.0-wd01.doc

But I doubt there are other issues regarding The repo you mentioned, some logs would be helpful.

**Comment by JaylinYu** [comment]
Now NanoMQ also supports MQTT 3.1
