### ISSUE TITLE
EMQ X Edge 與 NanoMQ 的分別？

### ISSUE THREAD

**Issue by alanko0511** [nanomq/nanomq#115]
你好，
我看到 EMQ X 有個叫 [EMQ X Edge](https://www.emqx.io/products/edge)，但單純看官網的話，好像與這個 NanoMQ 差不多，請問兩者有什麼分別？謝謝。

**Comment by JaylinYu** [comment]
你好，感謝垂詢
EMQ X Edge是EMQ X的精簡版。NanoMQ是重新C開發的broker，專門面向嵌入式設備，資源佔用更少，性能相同。目標是邊緣端的多協議消息總線。

**Comment by JaylinYu** [comment]
Moved to discussion channel
