### ISSUE TITLE
Enhance WIndows packaging CI (Debug to Release)

### ISSUE THREAD

**Issue by Egor-Li** [nanomq/nanomq#1232]
Hello,
I'm trying to run nanomq on Windows 11. When I start the broker it immediately shows an error which says that ucrtbased.dll is missing.
I have tried searching which software has this dll, and it should come with Microsoft Visual C++ Redistributable. I have all versions installed, and non of them provides this dll. 
I have downloaded this file separately from a website and put it in system32, but now nanomq gives an error that says that the application wasn't able to properly start.
Is there any way to launch nanomq broker on windows?

**Comment by JaylinYu** [comment]
I havent tested it on Win11, it works fine on Win10 and below.
Could you provide what error nanomq gives when start?

**Comment by Egor-Li** [comment]
I'm running the nanomq.exe located in \bin
Here's a screenshot of the error:
https://i.imgur.com/7lNVVTa.png

After pressing OK it repeats the same error, and after second press it closes. I have the ucrtbase.dll, but not ucrtbase**D**.dll

**Comment by Egor-Li** [comment]
Any ideas?

**Comment by JaylinYu** [comment]
NanoMQ requires ucrtbase.dll not ucrtbased.dll. If you experience such case, perhaps we wrongly released a debug version of window package. Could you try and old build here?
https://github.com/emqx/nanomq/releases/tag/0.12.2

**Comment by JaylinYu** [comment]
fixed in #1362

**Comment by JaylinYu** [comment]
plz have a try on incoming 0.19.0
