### ISSUE TITLE
nanomq enable sqlite compile error

### ISSUE THREAD

**Issue by landyu** [nanomq/nanomq#1291]
**Describe the bug**
on ubuntu-14.4 cross compile to armv7l linux with`CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++ cmake -G Ninja -DNNG_ENABLE_SQLITE=ON -DENABLE_RULE_ENGINE=ON ..` 
report error:
```
-- NanoMQ versions --
-- Configuring for NanoMQ version 0.18.0
-- Build NanoMQ with ACL support --
-- MODE [Release] --
-- Configuring for NNG version 1.6.0-pre
-- Building static libs.
 Check MQTT_QUIC_CLIENT support: OFF 
-- Test zt disabled (unconfigured)
-- Checking for module 'mysqlclient'
--   No package 'mysqlclient' found
CMake Error at /usr/share/cmake-3.24/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.24/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  nanomq/CMakeLists.txt:71 (pkg_check_modules)
```

** Environment Details **
 - NanoMQ version: 0.18.0
 - Operating system and version: 
    -  host: ubuntu-14.4
    - target: armv7l linux 3.4.39
 - Compiler and language used: arm-linux-gnueabi-gcc (Linaro GCC 4.9-2017.01) 4.9.4

**Client SDK**
nanomq-0.18.2 release source

**Comment by JaylinYu** [comment]
You need to install mysql lib before enabling rule-engine with MySQL

**Comment by landyu** [comment]
@JaylinYu as you said, the following steps is right?:

1. download sourcecode from [All Operating Systems (Generic) (Architecture Independent), Compressed TAR Archive](https://downloads.mysql.com/archives/c-c/)
2. cross compile with arm-gcc
3. include the libmysqlclient.so to nanomq
4. do make

**Comment by OdyWayne** [comment]
related to https://github.com/nanomq/nanomq/issues/1295.
