### ISSUE TITLE
Cross-compile MySQL connector + Feature request: Query bridging connection status

### ISSUE THREAD

**Issue by landyu** [nanomq/nanomq#1295]
- 运行环境描述
  - host：armv7l linux 32bit
  - nanomq：0.18.2，源码交叉编译版本
  - 由于交叉编译暂时无法编译sqlite、规则引擎特性。无法使用规则引擎把broker的启动、bridge的连接信息记录到本地
  - 本地mqtt client后启动，存在丢失$SYS/brokers/connected $SYS/brokers/disconnected消息的问题
  - 使用webhook转发bridge连接状态信息，存在本地http server后启动从而漏掉webhook请求的问题
- 问题：
  - 是否存在对borker的api调用获取本地nanomq的bridge连接状态
  - 或者是否存在别的方法可以随时查询nanomq的bridge连接状态

**Comment by JaylinYu** [comment]
肯定是可以进行交叉编译的 [nanomq-0.18.2-linux-armhf-full.rpm](https://github.com/emqx/nanomq/releases/download/0.18.2/nanomq-0.18.2-linux-armhf-full.rpm)，可以参考 CI。
本地mqtt client后启动，存在丢失$SYS/brokers/connected $SYS/brokers/disconnected消息的问题： 是指有上下线消息丢失吗？请提供细节和重现办法。

目前没有REST API查询，因为轮询方式会造成大量浪费。

**Comment by JaylinYu** [comment]
关于存储上下线消息到数据库的部分，如您需要，会计划推出一篇blog

**Comment by landyu** [comment]
> 肯定是可以进行交叉编译的 [nanomq-0.18.2-linux-armhf-full.rpm](https://github.com/emqx/nanomq/releases/download/0.18.2/nanomq-0.18.2-linux-armhf-full.rpm)，可以参考 CI。 本地mqtt client后启动，存在丢失$SYS/brokers/connected $SYS/brokers/disconnected消息的问题： 是指有上下线消息丢失吗？请提供细节和重现办法。
> 
> 目前没有REST API查询，因为轮询方式会造成大量浪费。

- 我这边是armv7l 的soc的linux版本，不支持rpm安装，我自己编译了一个可以运行但无法开启sqlite、rule功能
- 我说的获取不到$SYS/brokers/connected $SYS/brokers/disconnected的情况大概是这样的：
  - 嵌入式linux上电启动，nanomq服务率先启动并且bridge云端emqx成功，此时本地自有服务A还未启动
  - 本地服务A启动，以client连接到本地nanomq，这种情况下服务A无法知道bridge是否已经成功了

有没有可能提供类似的像`/api/v4/clients` 这样的接口，查询bridge返回一个`"conn_state": "connected"`的属性表示bridge连接成功了
```json
{
    "code": 0,
    "data": [
        {
            "client_id": "gatewaybroker-core-paho35598232186",
            "username": "gatewaybroker-core",
            "keepalive": 60,
            "conn_state": "connected",
            "clean_start": true,
            "proto_name": "MQTT",
            "proto_ver": 4
        },
        {
            "client_id": "mqttx_5494d15e_ws",
            "username": "ws-test",
            "keepalive": 60,
            "conn_state": "connected",
            "clean_start": true,
            "proto_name": "MQTT",
            "proto_ver": 5
        },
        {
            "client_id": "mqttx_fd748db1_tcp",
            "username": "test",
            "keepalive": 60,
            "conn_state": "connected",
            "clean_start": true,
            "proto_name": "MQTT",
            "proto_ver": 5
        },
        {
            "client_id": "mqttx_fd748db1",
            "username": "test",
            "keepalive": 60,
            "conn_state": "disconnected",
            "clean_start": true,
            "proto_name": "MQTT",
            "proto_ver": 4
        },
        {
            "client_id": "gatewaybroker-core-paho1420741410472",
            "username": "gatewaybroker-core",
            "keepalive": 60,
            "conn_state": "connected",
            "clean_start": true,
            "proto_name": "MQTT",
            "proto_ver": 4
        }
    ]
}
```

**Comment by landyu** [comment]
> 肯定是可以进行交叉编译的 [nanomq-0.18.2-linux-armhf-full.rpm](https://github.com/emqx/nanomq/releases/download/0.18.2/nanomq-0.18.2-linux-armhf-full.rpm)，可以参考 CI。

我找到你们的[如何对 Neuron 源码进行交叉编译](https://www.emqx.com/zh/blog/how-to-cross-compile-neuron-source-code)的博客，您这是否还有别的交叉编译的文档可以参考？

我这边交叉编译遇到的问题是:`No package 'mysqlclient' found`, 您这边方便提供下解决思路，谢谢！

**Comment by JaylinYu** [comment]
交叉编译和普通的C/C++工程一样，只需要指定工具链即可
No package 'mysqlclient' found 如之前的issue回复，需要安装 sudo apt install libmysqlclient-dev

**Comment by landyu** [comment]
> 交叉编译和普通的C/C++工程一样，只需要指定工具链即可 No package 'mysqlclient' found 如之前的issue回复，需要安装 sudo apt install libmysqlclient-dev

@JaylinYu 谢谢你的回复，之前已经安装了libmysqlclient-dev，我这边再研究下源码看看怎么解决

**Comment by JaylinYu** [comment]
最近我们才理解你的问题，如果是开启了了mysql，那么对应的libmysql的so也需要交叉编译，这确实有一定难度。会提供一个教程文档以作参考。

**Comment by JaylinYu** [comment]
[cross-compile-mysql-connector-c-270723-025632.pdf](https://github.com/emqx/nanomq/files/12178926/cross-compile-mysql-connector-c-270723-025632.pdf)
@landyu 请参考此文来完成MySQL功能的 交叉编译，如有不便多有抱歉

**Comment by JaylinYu** [comment]
目前推荐交叉编译mysql connector后与nanomq动态链接
