### ISSUE TITLE
auth_http

### ISSUE THREAD

**Issue by AetheWu** [nanomq/nanomq#1320]
**Describe the bug**

认证配置如下：
    sources = [
		{
			type = simple
			enable = true
			users = [
				{
					username = "admin"
					password = "public"
				},
				{
					username = "client"
					password = "public"
				}
			]
		},
		{
			type = http
			enable = true
			auth_req {
				url = "http://host.docker.internal:8088/mqtt/auth"
				method = POST
				headers.content-type = "application/json"
				params = {clientid = "%c", username = "%u", password = "%P"}
			}
			timeout = 5s
			connect_timeout = 5s
			pool_size = 32	
		}
	]
启动hauth_http后，认证链不生效，simple类型的认证没有起作用。
**Expected behavior**

根据认证链依次认证。

**Actual Behavior**
Describe what occurred.

**To Reproduce**
If possible include actual reproduction test code here.
Minimal C test cases are perferred.

** Environment Details **
 - NanoMQ version
 - Operating system and version
 - Compiler and language used
 - testing scenario

**Client SDK**
If possible include the mqtt sdk you used to connect to nanomq
Minimal C test cases are perferred.

**Additional context**

**Comment by JaylinYu** [comment]
Hi Bro  @AetheWu，I suspect you are the victim of our inconsistency doc. We are in a rushing mode of updating the Docs, for now, docs is not matched with the most updated version 0.18.2, if you are using such ver. Recommend to use the classical way of configuration `nanomq start --old_conf nanomq_old.conf`.

Hi 兄台， 我怀疑你被错误的文档误导了，目前nanomq正处在文档和配置重构阶段，文档里的HOCON 配置文件描述与之前发布的0.18.2 版本并不匹配，是我们即将发布的 0.19.0 版本。 目前推荐您使用 原有的配置文件格式：`nanomq start --old_conf nanomq_old.conf`。

**Comment by JaylinYu** [comment]
[nanomq-auth.txt](https://github.com/emqx/nanomq/files/11945936/nanomq-auth.txt)
My old configuration file is attached.
I can successfully query my HTTP server for authentication:
![Screenshot from 2023-07-04 15-24-14](https://github.com/emqx/nanomq/assets/64823539/fdebbf07-6634-4476-9b12-e5f930b28791)

**Comment by JaylinYu** [comment]
close due to idle
