### ISSUE TITLE
reload fail or server panic

### ISSUE THREAD

**Issue by ChanZany** [nanomq/nanomq#1324]
**Describe the bug**
This reload function has the following problems：
1. When the client calls reload successfully, the server side reports an error and the configuration of Load does not take effect
```CLI
nanomq reload --conf etc/nanomq.conf
reload succeed
```
```SERVER LOG
2023-07-01 10:10:19 [45753] DEBUG ../nanomq/cmd_proc.c:107 cmd_server_cb: recv cmd : {"cmd":"reload","conf_file":"etc/nanomq.conf","conf_type":2}
error: syntax error
```
2.  When the incoming configuration to be reloaded is as follows (nanomq_acl_new.conf does not exist), it will directly cause the SERVER program to crash
```nanomq.conf
auth {
    allow_anonymous = true
    no_match = allow
    deny_action = disconnect

    cache = {
        max_size = 32
        ttl = 1m
    }
    

# password = {include "etc/nanomq_pwd.conf"}
acl = {include "etc/nanomq_acl_new.conf"}
}
```
```server log
2023-07-01 10:10:19 [45753] DEBUG ../nanomq/cmd_proc.c:107 cmd_server_cb: recv cmd : {"cmd":"reload","conf_file":"etc/nanomq.conf","conf_type":2}
error: syntax error
error: syntax error
munmap_chunk(): invalid pointer
Aborted (core dumped)
 ```

** Environment Details **
 - NanoMQ version: 0.18.2
 - Operating system and version: ubuntu20.04
 - Compiler and language used: cmake
 - testing scenario: nanomqCLI

**Comment by JaylinYu** [comment]
The bug is identified. Thanks for reporting. 
The reload API is broken due to the full-scale refactoring of HOCON configuration file.
Will fix this in next release after 0.19.0

**Comment by JaylinYu** [comment]
Should be working after 0.19.1

**Comment by JaylinYu** [comment]
close due to no feedback
fix has been tested
