### ISSUE TITLE
Recommended pattern for multiple realtime stream processors for multiple connected clients

### ISSUE THREAD

**Issue by brentpicasso** [nanomq/nanomq#1421]
Hi, 

We've selected NanoMQ for our IoT telemetry recever.  In our design, multiple devices will connect to a single NanoMQ instance.   

What we want is a way to create a realtime data processor for each connected device.

![image](https://github.com/emqx/nanomq/assets/3267533/e0a38d1b-19c4-459a-8996-ea25068fd4ef)

Using the Python Paho Mqtt connector, we have a single handler for on_message.  
```
    client = mqtt.Client()
    client.on_connect = on_connect
    client.on_message = on_message
    client.connect(NANOMQ_HOST, NANOMQ_PORT, 60)
```
This implies that all messages for all devices will funnel through the same on_message() handler. 

What we want are separate on_message() events for each connected device, each handled by a thread/task.

Is this practical to do with the MQTT connector, or would the ZeroMQ connector be more efficient, possibly with a topic filter matching the device? 

Thank you for any help.

**Comment by JaylinYu** [comment]
Hi,

The issue you seeking for help is really a very common one for MQTT users. The lack of consuming power.
To my experience, One single python client can reach up to 200-300 msg/s subscribing rate. You need multiple MQTT clients to exceed this number with shared subscription on.

Another good news is, NanoSDK, the sibling project of NanoMQ provide you a high performance way to parallelly execute msg_cb, each callback will be handled by a unique thread, and all threads runs parallel. The upper limit is the msg rate of a single UNIX socket.

If you need more help, perhaps we can put it on a call.

**Comment by brentpicasso** [comment]
Hi, thank you very much for the reply. 

From the documentation, it appears that NanoSDK is designed to run in a separate process from NanoMQ.  Or can it run in the context of NanoMQ, within the same process?

**Comment by JaylinYu** [comment]
You really confuse me, NanoSDK is just like "Python Paho Mqtt connector", it is a MQTT SDK, (NanoSDK/NNG is more than that).
The MQTT SDK all run in a separate process. 

Of course, you can edit code of NanoMQ to make client embedded.
