### ISSUE TITLE
Nano clients disconnect when EMQX bridge disconnects

### ISSUE THREAD

**Issue by parkershute** [nanomq/nanomq#1460]
**Describe the bug**
When I disconnect the bridge through shutting down access to the EMQX broker the clients that I have connected to the Nano broker disconnect as well.

**Expected behavior**
When the connection between the Nano & EMQX broker is disrupted clients connected to the Nano broker will remain connected and publishing data to the Nano broker. That data will buffer on the Nano broker and transmit when the connection to EMQX is established again. 

**Actual Behavior**
I am working on testing various options for data persistence in the case of a failure to push to the cloud EMQX broker over the bridge. When I interrupt the connection between Nano and EMQX the clients that I have are disconnecting from the Nano broker itself. It should be noted that I have a HAProxy load balancer in front of the EQMX broker cluster. 
The behavior is seen in the clients themselves. The logs on the Nano broker indicate that the clients are still connected however the client will indicate it is disconnected and enter into the mode to attempt reconnects.

**To Reproduce**
Establish and EQMX broker with a HAProxy load balancer
Establish a Nano broker on another server and connect a bridge to EMQX
Establish a connection to the Nano broker via MQTTX
Establish a subscription to the EQMX broker
Publish from your MQTTX client to the Nano broker and verify the sub receives a message
Next find a way to break the connection on the bridge (I have tried shutting down HAProxy, closing listeners on EMQX, shutting down ports - all exhibit the same behavior of the bug)
Check your MQTTX client that is connected to Nano and see that it is disconnected
Check Nano logs and see it thinks the client is still there 

** Environment Details **
 - NanoMQ - nanomq-0.19.5-linux-arm64-sqlite.deb on Debain 12 on an AWS EC2
 - EQMX - 5.1.6 - on Ubuntu 22 on AWS EC2
 - HAProxy - 2.8.3 - on Ubuntu 22 on AWS EC2 
 - MQTTX - 1.9.6 - on my local machine

**Client SDK**
I am using the MQTTX client

**Comment by OdyWayne** [comment]
I can not reproduce your bug(note that I am not using HAProxy). Things work just fine, and I can trigger the expected behavior.  If you have more detailed information about how to reproduce, please let me know.

**Comment by JaylinYu** [comment]
The bridge connection have no way to affect locale clients of nanomq. This is simply impossible, please provide more detailed logs

**Comment by parkershute** [comment]
We believe we have tracked it down to HAProxy. But there are no logs that show the behavior. Without HAProxy it is working as expected. Something with the Load Balancer is not showing the disconnect in Nano, even when we turn the Load Balancer off.

**Comment by JaylinYu** [comment]
> We believe we have tracked it down to HAProxy. But there are no logs that show the behavior. Without HAProxy it is working as expected. Something with the Load Balancer is not showing the disconnect in Nano, even when we turn the Load Balancer off. 

LB could give a dummy tcp connection to client, in this case NanoMQ cannot identify the bridge link status correctly by itself. Because it simply doesnt reply, But at tcp level all looks normal. 
Here is why MQTT has its own keepalive
