### ISSUE TITLE
New bridge notification

### ISSUE THREAD

**Issue by JaylinYu** [nanomq/nanomq#1471]
when a client connect to nanomq broker after bridge has already connected successfully.
when a client connect to nanomq broker before bridge connect successfully.

**Comment by adarsh-jha-dev** [comment]
Hey @JaylinYu , I'd like to work on this issue, please assign this to me

**Comment by JaylinYu** [comment]
Sure!
Let me make you understand more about this issue in case you get it wrong.
user wants a way to know the state of bridging. In the previous version, we rely on the online/offline notification. However, things are getting messy when nanomq restarts. Client might connect after bridging is connected. Thus, we need to cache create a new notification way for users to check the state for bridging.
Either cache the online/offline msg of bridging client, or a new HTTP REST API

**Comment by JaylinYu** [comment]
dont plan this anymore
