### ISSUE TITLE
Update Twitter logo to its latest one(X).

### ISSUE THREAD

**Issue by niranjan-kurhade** [nanomq/nanomq#1502]
It's good to stay updated in the Tech World.
Hence, we should update the logo of Twitter to its latest one (X).

Screenshots-
![image](https://github.com/emqx/nanomq/assets/97905637/8de60fe1-d40a-4f06-9f9b-7aa23cfab424)

![image](https://github.com/emqx/nanomq/assets/97905637/79a0da7c-1a66-4311-a0a6-55df33d40189)

**Comment by niranjan-kurhade** [comment]
Please assign me this issue. I would like to fix this!

**Comment by JaylinYu** [comment]
Thanks for your enthusiasm. 
But the code of website  "nanomq.io" is located in another private repo. IDK how you would contribute.

Feel free to help us improve the docs!
