### ISSUE TITLE
docs compatibility for 'tip' in pure markdown

### ISSUE THREAD

**Issue by OdyWayne** [nanomq/nanomq#1528]
compatibility

**Additional context**
![image](https://github.com/emqx/nanomq/assets/53253973/19b17b2a-eada-40ee-b537-f4a4b1eaa687)
![image](https://github.com/emqx/nanomq/assets/53253973/c1319a38-0d67-441c-bb3e-468ecbaba478)

**Comment by JaylinYu** [comment]
not pretty sure what you mean by this

**Comment by OdyWayne** [comment]
vitepress syntax for `tip` is not compatible in vanilla markdown
example : at the beginning of https://github.com/nanomq/nanomq/blob/master/docs/zh_CN/bridges/tcp-bridge.md
![image](https://github.com/nanomq/nanomq/assets/53253973/bd89c1e9-59ad-46a5-8ca7-d03024c813ef)
