### ISSUE TITLE
Dynamic bridge never retry subscription if the first SUBSCRIBE attempts failed

### ISSUE THREAD

**Issue by takaomag** [nanomq/nanomq#1537]
**Describe the bug**
When one or more subscription entries are set dynamically but the SUBSCRIBE request(s) fails due to some network error, nanomq never retry subscription even after network is up.

**Expected behavior**
Whether the first attempts of dynamic subscription succeeds or fails due to some network error, nanomq should send subscription requests after network is up (that is, after MQTT CONNECT is successfully done).

**Actual Behavior**
Dynamic bridge never retry subscription if the first SUBSCRIBE attempts failed.

I feel this behavior is not a bug. It seems nanomq maintains just only succeeded dynamic subscriptions.
But in real use cases, I think such behavior is not user-friendly because the client must maintain the failed subscriptions list and continue to retry it.
It would be nice if dynamic subscription behaves just like static subscription (at this moment, static subscription seems to re-send subscription requests after MQTT CONNECT is successfully done).

**To Reproduce**
## 1. Edit nanomq.conf
```
system {
  num_taskq_thread = 0
  max_taskq_thread = 0
  parallel = 0
}

mqtt {
  max_packet_size = 1MB
  max_mqueue_len = 16
  max_inflight_window = 2048
  max_awaiting_rel = 10s
  await_rel_timeout = 10s
  retry_interval = 7s
  keepalive_multiplier = 1.25
  property_size = 32

}

listeners.tcp {
  bind = "0.0.0.0:50201"
}

listeners.ws {
  enable = false
}

listeners.wss {
  enable = false
}

sqlite {
  disk_cache_size = 102400
  mounted_file_path="/tmp/nanomq"
  flush_mem_threshold = 100
  resend_interval = 5000
}

http_server {
  port = 50200
  limit_conn = 32
  username = user
  password = pass
  auth_type = basic
}

log {
  to = [console]
  level = warn
}

webhook {
  enable = false
}

auth {
  allow_anonymous = true
  no_match = allow
  deny_action = ignore
  cache = {
    max_size = 32
    ttl = 1m
  }
}

bridges.mqtt.broker-0 {
  enable = true
  server = "mqtt-tcp://broker.hivemq.com:1883"
  # broker.emqx.io:1883 is not running at this moment.
  # server = "tls+mqtt-tcp://broker.emqx.io:8883"
  # server = "mqtt-quic://broker.emqx.io:14567"
  proto_ver = 5
  clientid="7dfa9ie3mbbr7qr36g9w5rq"
  keepalive = 10s
  clean_start = false
  username = org-1
  password = passwd

  # # Properties for MQTT V5
  conn_properties = {
    maximum_packet_size = 1048576
    receive_maximum = 16
    topic_alias_maximum = 64
    request_problem_infomation = 1
    request_response_infomation = 0
    session_expiry_interval = 182
    user_property = {
      project_name = product
    }
  }

  tls {
    enable = false
  }

  quic_keepalive = 120s
  quic_idle_timeout = 120s
  quic_discon_timeout = 20s
  quic_handshake_timeout = 60s
  quic_send_idle_timeout = 2s
  quic_initial_rtt_ms = 800ms
  quic_max_ack_delay_ms = 100ms
  hybrid_bridging = true
  quic_multi_stream = false
  quic_qos_priority = true
  quic_0rtt = true

  will {
    topic = "test0/org/1/edge/7dfa9ie3mbbr7qr36g9w5rqj6h632myun7e87crgf73an832zmf2/status"
    qos = 1
    retain = false
    payload = "{\"org_id\":1, \"machine_id\": \"7dfa9ie3mbbr7qr36g9w5rqj6h632myun7e87crgf73an832zmf2\"}"
    properties = {
      payload_format_indicator = 1
      message_expiry_interval = 182
      content_type = "application/json; charset=utf-8; msgType=\"Disconnected\""
      response_topic = ""
      correlation_data = ""
      will_delay_interval = 56
      user_property = {
        project_name = product
      }
    }
  }

  forwards = [
    {
      remote_topic = "test0/org/1/edge/7dfa9ie3mbbr7qr36g9w5rqj6h632myun7e87crgf73an832zmf2/status"
      local_topic = "local/edge/status"
      qos = 0
    }
  ]

  max_parallel_processes = 2
  max_send_queue_len = 32
  max_recv_queue_len = 128
}

bridges.mqtt.cache {
  disk_cache_size = 102400
  mounted_file_path="/tmp/nanomq"
  flush_mem_threshold = 100
  resend_interval = 5000
}
```

## 2. Start nanomq with the above configuration
`nanomq start --conf nanomq.conf`

## 4. Set subscription entry(s) dynamically
```
curl --basic -u user:pass --location 'http://localhost:50200/api/v4/bridges/sub/broker-0' \
--header 'Content-Type: application/json' \
--data '{
  "data": {
    "subscription": [
      {
        "remote_topic": "test0/org/1/edge/7dfa9ie3mbbr7qr36g9w5rqj6h632myun7e87crgf73an832zmf2/cmd",
        "local_topic": "local/edge/cmd",
        "qos": 1
      }
    ]
  }
}'
```

It takes some time. maybe due to link-down.
The return value: `{"code":108}`

## 6. nanomq sends an MQTT CONNECT message, but ..
nanomq never sends MQTT SUBSCRIBE messages for the dynamically added subscription.

**Environment Details**
 - NanoMQ version: 0.20.8
 - Operating system and version: Archlinux (kernel 6.6.1-arch1-1)
 - Compiler and language used: GCC 13.2.1, cmake 3.27.8, ninja 1.11.1
 - testing scenario

**How to build the tested nanomq**
```
yay -S --needed --removemake --cleanafter cmake ninja boost
sudo rm -rf /opt/local/nanomq \
&& sudo rm -rf /var/tmp/nanomq-build \
&& mkdir /var/tmp/nanomq-build \
&& cd /var/tmp/nanomq-build \
&& git clone https://github.com/emqx/nanomq.git -b 0.20.8 \
&& cd nanomq \
&& git submodule update --init --recursive
cmake \
  -B build_nanomq \
  -G Ninja \
  -DCMAKE_INSTALL_PREFIX="" \
  -DCMAKE_BUILD_TYPE=None \
  -DNNG_ENABLE_TLS=ON \
  -DNNG_ENABLE_SQLITE=ON \
  -DNNG_ENABLE_QUIC=ON \
  -DQUIC_BUILD_SHARED=OFF \
  -DENABLE_JWT=ON \
  -DENABLE_RULE_ENGINE=ON \
  -DENABLE_ACL=ON \
  -DENABLE_SYSLOG=ON \
&& ninja -C build_nanomq \
&& DESTDIR=/opt/local/nanomq sudo -E ninja -C build_nanomq install \
&& sudo mv build_nanomq/install_manifest.txt /opt/local/nanomq/. \
&& cd /var/tmp \
&& rm -rf /var/tmp/nanomq-build
```

**Comment by takaomag** [comment]
Thank you for your reply.

- Persisting the dynamic sub-topic to configuration
I totally agree with the way you think.

- Putting dynamical sub-topics to memory
As you say, currently nanomq seems some store subscription structs in memory **after** it receives the SUBACK.
But I feel it would be great if such struct is stored in memory **before** it sends the SUBSCRIBE request.

When a dynamic subscription is triggered by an http api, the subscription request may fail due to temporary network error.
Currently, nanomq has not responsibility for the retry, which means client application must continue to call the subscription api periodically until `code==0`.

If nanomq stores subscription struct **before** it sends the SUBSCRIBE request and has a responsibility for the retry, client application can be easy.

Anyway, I understand the nanomq design. This is just a future request.

**Comment by JaylinYu** [comment]
It is not reasonable for a broker to keep resending SUBSCRIBE packets. it doesn't know when to stop, and how to response to HTTP requests. It introduces non-necessary complexity and security concerns into the project.
However, it is a different story if there is a business case (request).
