### ISSUE TITLE
Feature: http api response 404

### ISSUE THREAD

**Issue by caimmy** [nanomq/nanomq#1538]
**Describe the bug**
When I call certain HTTP API interfaces, the nanomq server returns a 404 error. These interfaces include 
 /api/v4/mqtt/subscribe  
/api/v4/mqtt/unsubscribe  
/api/v4/mqtt/publish_batch  
/api/v4/mqtt/subscribe_batch

** Environment Details **
 - NanoMQ version is 0.20.6
- I started the nanomq service through docker , and the image version is emqx/nanomq:0.20.6-full

Thanks for look at this problem.

**Comment by OdyWayne** [comment]
Just tested for **/api/v4/mqtt/publish_batch**, it works fine. More detailed information will be appreciated. As for the rest of them, they are indeed not available now, we close it for some reason.
