### ISSUE TITLE
Disabling TCP doesn't work

### ISSUE THREAD

**Issue by lizziemac** [nanomq/nanomq#1563]
**Describe the bug**
When I set the listeners.tcp.enable flag to false, I’m still able to connect to the broker at the insecure port (see below config). I'm using the default configuration file located at `/etc/nanomq.conf`, and running the command with `nanomq start`.

**Expected behavior**
I should not be able to connect to MQTT/nanomq via TCP when `listeners.tcp.enable = false`

**Actual Behavior**
I was able to connect to nanomq via TCP when `listeners.tcp.enable = false`

**To Reproduce**
1. Set your configuration in `/etc/nanomq.conf`, and enable SSL with some certs
    ```hocon
    listeners.tcp {
          enable = false
    }
    ```
2. Start the nanomq server
    ```
    nanomq start
    ```
3. In a separate window (or in MQTTX), subscribe to the topic without using SSL. You will see a successful connection, and will then be able to see any traffic published to that topic, including via SSL.
    ```
    nanomq_cli sub -t my/topic/#
    connect_cb: mqtt-tcp://127.0.0.1:1883 connect result: 0
    ```

**Environment Details**
 - NanoMQ version: `v0.20.8-4`
 - Operating system and version: `Linux aarch64` - custom with linux kernel of `5.4.215`
 - Compiler and language used: N/A - installed with:
     ```
     wget https://www.emqx.com/en/downloads/nanomq/0.20.8/nanomq-0.20.8-linux-arm64.rpm
     rpm -i nanomq-0.20.8-linux-arm64.rpm
     ```
 - testing scenario: `not sure what this is`

**Client SDK**
NanoMQ

**Additional context**
I want to use/enable exclusively SSL

**Comment by OdyWayne** [comment]
we use a default url to enable tcp in case of  misusage.  And the conf you used `listeners.tcp {enable = false}` was not a official conf option. But we will make it happen.

**Comment by OdyWayne** [comment]
The latest master branch can disable TCP now, and just conf like `listeners.tcp {enable = false}`. You can compile yourself or wait for our upcoming release.

**Comment by OdyWayne** [comment]
You can disable TCP by removing all conf for TCP now, and this is the way we recommend.

**Comment by JaylinYu** [comment]
I believe this has been fixed, will pub a new release in Jan
