### ISSUE TITLE
enhance docs 关于文档的完善

### ISSUE THREAD

**Issue by shu7734** [nanomq/nanomq#1581]
在查看文档时，看到
ACL相关的内容
https://nanomq.io/docs/zh/latest/access-control/acl.html
`["$SYS/#", "#"]`
这个语法，$SYS之类的内置变量，以及基础语法，去哪里查？
我怎么允许用户访问以他用户名开头的topics？

**Comment by JaylinYu** [comment]
感谢督促，最近忙于新功能和商业客户交付。
后续会陆续更新。也希望大家能一起更新

**Comment by OdyWayne** [comment]
> 这个语法，$SYS之类的内置变量，以及基础语法，去哪里查？

这是MQTT协议规定的通配符规则，更详细的介绍可以参考: https://www.emqx.com/zh/blog/advanced-features-of-mqtt-topics
 > 我怎么允许用户访问以他用户名开头的topics？

例:  允许用户名为`usr`的用户订阅 `usr/`开头的`topic` --> `{"permit": "allow", "username": "usr", "action": "subscribe", "topics": ["usr/#"]}`

**Comment by JaylinYu** [comment]
doc has been added
