### ISSUE TITLE
Clientid not checked when create new client connection

### ISSUE THREAD

**Issue by mxchipwanges** [nanomq/nanomq#1619]
**Describe the bug**
Two client connected with the same client id

**Expected behavior**
Close the previous connection before  a new connection with same client id created.

**Actual Behavior**
Two  client can be connected.

**To Reproduce**
1. Start broker: nanomq start
2. Client1 connet with MQTTX, clientid: mqttx_1234
3. Client2 connet with MQTTX, clientid: mqttx_1234

**Environment Details**
 - NanoMQ nanomq-0.19.5-linux-armhf-sqlite.deb
 - Operating system and version:  STOpenLinux

**Client SDK**
MQTTX
SSL/TLS disabled

**Additional context**

**Comment by JaylinYu** [comment]
this is already fixed in master branch

**Comment by mxchipwanges** [comment]
When will the next release?

**Comment by JaylinYu** [comment]
Tomorrow
