### ISSUE TITLE
ASAN report SEGV on Unknown address

### ISSUE THREAD

**Issue by JaylinYu** [nanomq/nanomq#163]
Unsafe bug when doing Sub

**Comment by JaylinYu** [comment]
"nanomq.conf ./etc/nanomq.conf" file not found or unreadable
AddressSanitizer:DEADLYSIGNAL
=================================================================
==401030==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x5593be479db1 bp 0x7f949d4fc6c0 sp 0x7f949d4fc6a0 T3)
==401030==The signal is caused by a READ memory access.
==401030==Hint: address points to the zero page.
    #0 0x5593be479db1 in std::equal_to<unsigned int>::operator()(unsigned int const&, unsigned int const&) const /usr/include/c++/10/bits/stl_function.h:356
    #1 0x5593be4780f8 in std::__detail::_Hashtable_base<unsigned int, std::pair<unsigned int const, topic_queue*>, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Hashtable_traits<false, false, true> >::_M_equals(unsigned int const&, unsigned long, std::__detail::_Hash_node<std::pair<unsigned int const, topic_queue*>, false>*) const /usr/include/c++/10/bits/hashtable_policy.h:1804
    #2 0x5593be47533c in std::_Hashtable<unsigned int, std::pair<unsigned int const, topic_queue*>, std::allocator<std::pair<unsigned int const, topic_queue*> >, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_before_node(unsigned long, unsigned int const&, unsigned long) const /usr/include/c++/10/bits/hashtable.h:1580
    #3 0x5593be4727f5 in std::_Hashtable<unsigned int, std::pair<unsigned int const, topic_queue*>, std::allocator<std::pair<unsigned int const, topic_queue*> >, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_node(unsigned long, unsigned int const&, unsigned long) const /usr/include/c++/10/bits/hashtable.h:693
    #4 0x5593be47027f in std::_Hashtable<unsigned int, std::pair<unsigned int const, topic_queue*>, std::allocator<std::pair<unsigned int const, topic_queue*> >, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::find(unsigned int const&) /usr/include/c++/10/bits/hashtable.h:1454
    #5 0x5593be46ebfc in std::unordered_map<unsigned int, topic_queue*, std::hash<unsigned int>, std::equal_to<unsigned int>, std::allocator<std::pair<unsigned int const, topic_queue*> > >::find(unsigned int const&) /usr/include/c++/10/bits/unordered_map.h:920
    #6 0x5593be46d95d in mqtt_hash<unsigned int, topic_queue*>::find(unsigned int const&) ../nanolib/hash.cc:59
    #7 0x5593be46aa5f in check_id ../nanolib/hash.cc:431
    #8 0x5593be46a112 in check_topic ../nanolib/hash.cc:338
    #9 0x5593be49797a in sub_ctx_handle ../nanomq/sub_handler.c:311
    #10 0x5593be49b247 in server_cb ../nanomq/apps/broker.c:176
    #11 0x5593be4ca7d0 in nni_taskq_thread ../nng/src/core/taskq.c:50
    #12 0x5593be4cba3a in nni_thr_wrap ../nng/src/core/thread.c:94
    #13 0x5593be4d4462 in nni_plat_thr_main ../nng/src/platform/posix/posix_thread.c:218
    #14 0x7f94a1fb758f in start_thread nptl/pthread_create.c:463
    #15 0x7f94a1b5f222 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x119222)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /usr/include/c++/10/bits/stl_function.h:356 in std::equal_to<unsigned int>::operator()(unsigned int const&, unsigned int const&) const
Thread T3 (nng:task) created by T0 here:
    #0 0x7f94a2027a65 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x5593be4d4592 in nni_plat_thr_init ../nng/src/platform/posix/posix_thread.c:231
    #2 0x5593be4cbce3 in nni_thr_init ../nng/src/core/thread.c:121
    #3 0x5593be4caaef in nni_taskq_init ../nng/src/core/taskq.c:95
    #4 0x5593be4cb70a in nni_taskq_sys_init ../nng/src/core/taskq.c:284
    #5 0x5593be4b56bf in nni_init_helper ../nng/src/core/init.c:41
    #6 0x5593be4d4897 in nni_plat_init ../nng/src/platform/posix/posix_thread.c:368
    #7 0x5593be4b5776 in nni_init ../nng/src/core/init.c:61
    #8 0x5593be4bfd6c in nni_proto_mqtt_open ../nng/src/core/protocol.c:79
    #9 0x5593be4dd33f in nng_nano_tcp0_open ../nng/src/sp/protocol/reqrep0/nano_tcp.c:1272
    #10 0x5593be49d8b2 in broker ../nanomq/apps/broker.c:454
    #11 0x5593be49f5a9 in broker_start ../nanomq/apps/broker.c:639
    #12 0x5593be490864 in main ../nanomq/nanomq.c:163
    #13 0x7f94a1a6ecb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)

**Comment by wanghaEMQ** [comment]
What's your test case?
