### ISSUE TITLE
Windows: Is the libwinpthread-1.dll necessary for running nanomq broker

### ISSUE THREAD

**Issue by michaelcplusplus** [nanomq/nanomq#1631]
**Question**

Is the DLL libwinpthread-1.dll required for operation on Windows? I cannot see that the DLL is loaded in processexplorer.

![image](https://github.com/nanomq/nanomq/assets/24432169/fb08321a-049e-4e6d-a1a2-b824b9674ba4)

**Environment Details**
 - NanoMQ v0.20.8-4
 - Windows 10

**Comment by JaylinYu** [comment]
sure, it does. perhaps the pthread is wrapped with other dll.
not an expert on win to tell.

**Comment by michaelcplusplus** [comment]
Thanks
