### ISSUE TITLE
Retained messages behavior at broker restart

### ISSUE THREAD

**Issue by michaelcplusplus** [nanomq/nanomq#1632]
**Question**
Can retained messages be persisted so that they are still available after a nanomq Broker restart?

**Environment Details**
 - NanoMQ v0.20.8-4
 - Windows Server 2019

**Comment by JaylinYu** [comment]
This is a planned feature. Persist retain msg to SQLite, reload them when restarting the broker.

**Comment by JaylinYu** [comment]
just recall... 
this is already implemented here https://github.com/nanomq/NanoNNG/pull/455. But we don't have time to add some tutorials to docs.....

**Comment by michaelcplusplus** [comment]
How to configure this feature?
A simple example would help me a lot.
Best regards
Michael

**Comment by JaylinYu** [comment]
Apologize for incomplete guidance.
please refer to https://nanomq.io/docs/en/latest/config-description/broker.html#cache

just add following section to your config:

`sqlite {
        disk_cache_size = 102400
        mounted_file_path="/tmp/"
        flush_mem_threshold = 100
        resend_interval = 5000
}`


then it will automatically turn on SQLite cache, including put retain msg to sqlite.

**Comment by JaylinYu** [comment]
plz elaborate more in doc @OdyWayne  for @michaelcplusplus

**Comment by michaelcplusplus** [comment]
Thank you. It works now.
I guess that it is not possible to set a message expire interval for retained messages.

**Comment by JaylinYu** [comment]
That requires periodically searching table action. shall be unacceptable in terms of performance

**Comment by JaylinYu** [comment]
@michaelcplusplus recall again....
the logic is decoupled... Not hard to make it happen
it is done in https://github.com/nanomq/nanomq/pull/1644
plz use new release 0.21.1

**Comment by michaelcplusplus** [comment]
Thanks. How to configure this option?

**Comment by JaylinYu** [comment]
The msg expiry interval is set by client.

**Comment by michaelcplusplus** [comment]
Thank you for your support
