### ISSUE TITLE
Feature Request: HTTP Interface of acl_req 

### ISSUE THREAD

**Issue by solekubi** [nanomq/nanomq#1633]
测试的时候发现：
   1、连接时，可以跑到auth，这部分正常
   2、无法跑到super_req这个，请问这个接口是何时才会被调用？
   3、使用MQTTX工具进行发布订阅时，都无法跑进acl接口，是否需求其他配置
![image](https://github.com/nanomq/nanomq/assets/15035534/99dce60a-e3e2-48f6-a9d9-f8b2d97e9269)
![image](https://github.com/nanomq/nanomq/assets/15035534/298358e6-a073-4fea-8e71-e88787b6c0f3)
![image](https://github.com/nanomq/nanomq/assets/15035534/5ec18e9e-69bb-42a7-8364-75f0065879ab)

具体的日志：[nanomq.log](https://github.com/nanomq/nanomq/files/14048602/nanomq.log)

nanomq版本：
用的docker镜像：emqx/nanomq:latest
![image](https://github.com/nanomq/nanomq/assets/15035534/2673632a-3f9a-4a29-b779-5b8946a4753f)

**Comment by OdyWayne** [comment]
1. ACL：需要增加对ACL规则的配置，添加类似`acl = {include "/etc/nanomq_acl.conf"}`。详细配置请参考[配置](https://nanomq.io/docs/zh/latest/config-description/acl.html)。
2. `super_req`：目前该功能未开放。

**Comment by solekubi** [comment]
> 1. ACL：需要增加对ACL规则的配置，添加类似`acl = {include "/etc/nanomq_acl.conf"}`。详细配置请参考[配置](https://nanomq.io/docs/zh/latest/config-description/acl.html)。
> 
> 2. `super_req`：目前该功能未开放。

我想通过http的方式进行acl鉴权，之前的测试发现，无论订阅还是发布，都无法调用acl_req中配置的接口

**Comment by JaylinYu** [comment]
HTTP 接口还不适用于 acl_req， 未实现完成，目前只能用于Authtication. 这将转成一个feature request

**Comment by JaylinYu** [comment]
Now it is done
