### ISSUE TITLE
MemLeak in parse conf

### ISSUE THREAD

**Issue by OdyWayne** [nanomq/nanomq#1652]
**Describe the bug**
There will be memleak if I duplicate the same configuration.

**To Reproduce**
Write any configuration twice like webhook or http sever.

**Comment by JaylinYu** [comment]
plz add more context with ASAN logs

**Comment by OdyWayne** [comment]
=================================================================
	==41566==ERROR: LeakSanitizer: detected memory leaks

	Direct leak of 39 byte(s) in 4 object(s) allocated from:
    	#0 0x7ff0c70b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    	#1 0x5566894871df in cJSON_strdup /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/cJSON.c:205
    	#2 0x55668948f37c in add_item_to_object /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/cJSON.c:1944
    	#3 0x55668948f53c in cJSON_AddItemToObject /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/cJSON.c:1966
    	#4 0x55668955b185 in yyparse /home/hermann/Documents/hermannDocuments/nanomq/build/nng/parser.y:87
    	#5 0x5566894e8ab4 in hocon_parse_file /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/hocon.c:163
    	#6 0x5566894c3cda in conf_parse_ver2 /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/conf_ver2.c:1512
    	#7 0x5566891b14df in broker_start /home/hermann/Documents/hermannDocuments/nanomq/nanomq/apps/broker.c:1677
    	#8 0x5566891a5b4f in main /home/hermann/Documents/hermannDocuments/nanomq/nanomq/nanomq.c:142
    	#9 0x7ff0c6c29d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
	
	Direct leak of 32 byte(s) in 1 object(s) allocated from:
    	#0 0x7ff0c70b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    	#1 0x5566894871df in cJSON_strdup /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/cJSON.c:205
    	#2 0x556689491555 in cJSON_Duplicate /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/cJSON.c:2609
    	#3 0x5566894916e9 in cJSON_Duplicate /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/cJSON.c:2631
    	#4 0x5566894e7db9 in deduplication_and_merging /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/hocon.c:105
    	#5 0x5566894e8913 in deduplication_and_merging /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/hocon.c:145
    	#6 0x5566894e8bab in hocon_parse_file /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/hocon.c:170
    	#7 0x5566894c3cda in conf_parse_ver2 /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/conf_ver2.c:1512
    	#8 0x5566891b14df in broker_start /home/hermann/Documents/hermannDocuments/nanomq/nanomq/apps/broker.c:1677
    	#9 0x5566891a5b4f in main /home/hermann/Documents/hermannDocuments/nanomq/nanomq/nanomq.c:142
    	#10 0x7ff0c6c29d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
	
	Direct leak of 19 byte(s) in 3 object(s) allocated from:
	    #0 0x7ff0c70b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
	    #1 0x5566894871df in cJSON_strdup /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/cJSON.c:205
   	    #2 0x5566894908a5 in cJSON_CreateString /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/cJSON.c:2369
	    #3 0x55668955ac1e in yyparse /home/hermann/Documents/hermannDocuments/nanomq/build/nng/parser.y:65
	    #4 0x5566894e8ab4 in hocon_parse_file /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/hocon.c:163
	    #5 0x5566894c3cda in conf_parse_ver2 /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/conf_ver2.c:1512
	    #6 0x5566891b14df in broker_start /home/hermann/Documents/hermannDocuments/nanomq/nanomq/apps/broker.c:1677
	    #7 0x5566891a5b4f in main /home/hermann/Documents/hermannDocuments/nanomq/nanomq/nanomq.c:142
	    #8 0x7ff0c6c29d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
	
	Direct leak of 8 byte(s) in 1 object(s) allocated from:
	    #0 0x7ff0c70b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
	    #1 0x5566894871df in cJSON_strdup /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/cJSON.c:205
	    #2 0x556689491655 in cJSON_Duplicate /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/cJSON.c:2618
	    #3 0x5566894916e9 in cJSON_Duplicate /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/cJSON.c:2631
	    #4 0x5566894e7db9 in deduplication_and_merging /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/hocon.c:105
	    #5 0x5566894e8913 in deduplication_and_merging /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/hocon.c:145
	    #6 0x5566894e8bab in hocon_parse_file /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/hocon.c:170
	    #7 0x5566894c3cda in conf_parse_ver2 /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/conf_ver2.c:1512
	    #8 0x5566891b14df in broker_start /home/hermann/Documents/hermannDocuments/nanomq/nanomq/apps/broker.c:1677
	    #9 0x5566891a5b4f in main /home/hermann/Documents/hermannDocuments/nanomq/nanomq/nanomq.c:142
	    #10 0x7ff0c6c29d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
	
	Direct leak of 5 byte(s) in 1 object(s) allocated from:
	    #0 0x7ff0c70b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
	    #1 0x5566894871df in cJSON_strdup /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/cJSON.c:205
	    #2 0x55668948f37c in add_item_to_object /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/cJSON.c:1944
	    #3 0x55668948f53c in cJSON_AddItemToObject /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/cJSON.c:1966
	    #4 0x55668955afe9 in yyparse /home/hermann/Documents/hermannDocuments/nanomq/build/nng/parser.y:84
	    #5 0x5566894e8ab4 in hocon_parse_file /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/hocon.c:163
	    #6 0x5566894c3cda in conf_parse_ver2 /home/hermann/Documents/hermannDocuments/nanomq/nng/src/supplemental/nanolib/conf_ver2.c:1512
	    #7 0x5566891b14df in broker_start /home/hermann/Documents/hermannDocuments/nanomq/nanomq/apps/broker.c:1677
	    #8 0x5566891a5b4f in main /home/hermann/Documents/hermannDocuments/nanomq/nanomq/nanomq.c:142
	    #9 0x7ff0c6c29d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
	
	SUMMARY: AddressSanitizer: 103 byte(s) leaked in 10 allocation(s).
