### ISSUE TITLE
mqtt client can't connect

### ISSUE THREAD

**Issue by zhouji0212** [nanomq/nanomq#1657]
log like that..
![c73de6292314c41355ee47dbad3f347](https://github.com/nanomq/nanomq/assets/4176951/2bbb119d-c229-4603-8d4c-c1ae0b823a6c)

**Comment by JaylinYu** [comment]
The sdk u using is sending malformed QoS packet. 
Plz fire an issue against them. 
Packetid shall not be 0.
The rest log says client timeouts

**Comment by OdyWayne** [comment]
this is more like a issue from the client side
