### ISSUE TITLE
nanomq version num incorrect

### ISSUE THREAD

**Issue by mxchipwanges** [nanomq/nanomq#1664]
**Describe the bug**
version num not changed (still 0.21.1-3) in  release 0.21.2

in file include/version.h
#define NANO_VER_MAJOR 0
#define NANO_VER_MINOR 21
#define NANO_VER_PATCH 1
#define NANO_VER_ID_SHORT "3"

**Expected behavior**
Update version to 0.21.2

**Actual Behavior**
Describe what occurred.

**To Reproduce**
If possible include actual reproduction test code here.
Minimal C test cases are perferred.

nanomq -v

**Environment Details**
 - NanoMQ version:   release 0.21.2
 - Operating system and version
 - Compiler and language used
 - testing scenario

**Client SDK**
If possible include the mqtt sdk you used to connect to nanomq
Minimal C test cases are perferred.

**Additional context**

**Comment by JaylinYu** [comment]
ok my mistake
