### ISSUE TITLE
Support wildcard in remote topic

### ISSUE THREAD

**Issue by lovepluskaka** [nanomq/nanomq#1684]
Is it possible to make the remote_topic of the bridge support wildcard?
Such as
```
{
   remote_topic = "topic1/#"
   local_topic = "topic1/#"
}
```
User can bridge the topic1/1 、topic1/2、 ...... topic/N to remote in one config.
This feature can reduce the amount of configuration work.

**Comment by renvissvnce** [comment]
nanomq already supports wildcards. Based on your example the solution looks like this

for forward:
{
   remote_topic = ""
   local_topic = "topic1/#"
}

for subscription 
{
   remote_topic = "topic1/#"
   local_topic = ""
}

for more info check this article.
https://nanomq.io/docs/en/latest/config-description/bridges.html#configuration-items

**Comment by lovepluskaka** [comment]
Thanks! It seems works.

**Comment by aitorroca** [comment]
> nanomq already supports wildcards. Based on your example the solution looks like this
> 
> for forward: { remote_topic = "" local_topic = "topic1/#" }
> 
> for subscription { remote_topic = "topic1/#" local_topic = "" }
> 
> for more info check this article. https://nanomq.io/docs/en/latest/config-description/bridges.html#configuration-items

It works, but doesn't work if you try to rewrite the topic with a wildcard:

  forwards = [
    {
      remote_topic = "device_id/topic1/#"
      local_topic = "topic1/#"
    },
    ]
    
    Shows:
    
    2024-04-13 16:47:23 [1] ERROR /home/runner/work/nanomq/nanomq/nng/src/supplemental/nanolib/conf_ver2.c:970 conf_bridge_node_parse: No wildcard +/# should be contained in remote topic in forward rules.
