### ISSUE TITLE
Can we switch listeners.ssl cert generate level?

### ISSUE THREAD

**Issue by Xianhuii** [nanomq/nanomq#1693]
**Is your feature request related to a problem? Please describe.**
Config listeners.ssl on Linux (using Docker compose):
`listeners.ssl {
    bind = "0.0.0.0:8883"
    keyfile = "/etc/certs/key.pem"
    certfile = "/etc/certs/cert.pem"
    cacertfile = "/etc/certs/cacert.pem"
    verify_peer = true
    fail_if_no_peer_cert = true
}`

Run `docker start`, it reports error:
`FATAL /nanomq/nanomq/apps/broker.c:1122: nng_listener_create tls`

**Describe the solution you'd like**
Found from another issue: https://github.com/nanomq/nanomq/issues/1577. 
This error may cause by cert level, but we can't change cert. Can nanomq switch cert verify level?

**Comment by JaylinYu** [comment]
Not sure what you mean here. Issue 1577 is not related to your case, that's a client verification error.

FATAL /nanomq/nanomq/apps/broker.c:1122: nng_listener_create tls 

This looks like you are using a docker ver that doesn't support TLS.

**Comment by JaylinYu** [comment]
close due to inactive
