### ISSUE TITLE
Bridge not works and make crash nanomq on start (wrong config syntax)

### ISSUE THREAD

**Issue by rafbi77** [nanomq/nanomq#1705]
**Describe the bug**
Process nanomq not starting in **daemon** mode. Null in logs. Bridge not works and make crash. 

nanomq start --conf /etc/nanomq.conf -d

**Expected behavior**
Process nanomq  starting

**Actual Behavior**
Proces not starting

**To Reproduce**
Reproduction config:

mqtt {
    property_size = 32
    max_packet_size = 10KB
    max_mqueue_len = 2048
    retry_interval = 10s
    keepalive_multiplier = 1.25
    max_inflight_window = 2048
    max_awaiting_rel = 10s
    await_rel_timeout = 10s
}

listeners.tcp {
    bind = "0.0.0.0:1883"
}

listeners.ws {
    bind = "0.0.0.0:8083/mqtt"
}

http_server {
    port = 8081
    limit_conn = 2
    username = aqq
    password = aqq
    auth_type = basic
    jwt {
        public.keyfile = "/etc/certs/jwt/jwtRS256.key.pub"
    }
}

auth {
    allow_anonymous = false
    no_match = allow
    deny_action = ignore
    cache = {
        max_size = 32
        ttl = 1m
    }
    password = {include "/etc/nanomq_pwd.conf"}
}

log {
    to = [file, console]
    level = error
    dir = "/home/pi/logs"
    file = "nanomq.log"
    rotation {
        size = 10MB
        count = 3
    }
}

bridges.mqtt.emqx1 {
    server = "mqtt-tcp://146.XX.XX.XX:1883"
    proto_ver = 4
    keepalive = 60s
    clean_start = false
    username = null
    password = aqq
    forwards = aqq
        {
            remote_topic = ""
            local_topic = "#"
            qos = 0
        }
    ]
    max_parallel_processes = 4
    max_send_queue_len = 128
    max_recv_queue_len = 32
}

**Environment Details**
 - NanoMQ version 0.21.6 arm64
 - Rpi5 Rasbian bookworm  

**Additional context**
When remove section bridges.mqtt.emqx1 process in daemon mode starting fine.

**Comment by JaylinYu** [comment]
there is a "[" missing in your birdge configuration. Everything works fine after I fix this.

And nanomq shall not crash due to wrong config, at least not in my raspberry PI. if it indeed crash on booting at your board, plz provide dump file, or modify log level to debug for more information.

**Comment by rafbi77** [comment]
1. I check. My config is fine (github editor eat my "["). That's not it. 
2. When try start in daemon mode log is empty in debug.  
3. After further analysis, it is something with rpi permissions (open port in daemon mode, open logs etc). 
4. Maybe this will be useful to someone. My workaround is as follows:
Im running nanomq in systemd daemon (need aslo boot austostart):

**My file nanomq.service:**

[Unit]
Description=Nanomq daemon
After=network.target

[Service]
Type=simple
Environment=HOME=/home/pi
ExecStart=nanomq start --conf /etc/nanomq.conf
ExecStop=nanomq stop

[Install]
WantedBy=multi-user.target

**start proces:**
sudo systemctl start nanomq.service

And work is fine.

**Comment by JaylinYu** [comment]
If it was permission issue, nanomq shall complain on console, I guess you missed that information due to booting sequence.
anyway, glad you find out. 
close this.
