### ISSUE TITLE
update config_update using Http server api/v4  crash server  

### ISSUE THREAD

**Issue by amcharhal** [nanomq/nanomq#1707]
Run this HTTP https://nanomq.io/docs/en/latest/api/v4.html#update-configuration-file  request and you will see the NanoMQ server crash

 INFO  /home/runner/work/nanomq/nanomq/nanomq/rest_api.c:2591 update_config: Writting new config to (null)

 ERROR /home/runner/work/nanomq/nanomq/nanomq/apps/broker.c:104 sig_handler: signal signumber: 11 received!

**Comment by amcharhal** [comment]
I see in line 2591 log_info("Writting new config to %s", config->conf_file);   
config->config_file is null !!

**Comment by RanMaoyi** [comment]
Thanks for the feedback, it has been reproduced locally, and the patch is on the way:)
