### ISSUE TITLE
HTTP Authentication: acl_req not working

### ISSUE THREAD

**Issue by ennorehling** [nanomq/nanomq#1708]
**Describe the bug**
I am trying to configure the auth.http_auth.acl_req settings in nanomq.conf to delegate ACL checks to an external service, rather than use the static nanomq_acl.conf file. I did this before with the auth.http_auth.auth_req settings, and NanoMQ is calling my service as expected, and using the response status to allow/deny connections. But the acl endpoint never gets called, and all access is allowed.

**Expected behavior**
I expect NanoMQ to call the configured external endpoint, and accept or deny publish or subscribe requests based on the response (response code 20x vs 40X).

**Actual Behavior**
The configured endpoint is never called, all attempts to publish or subscribe to a topic are allowed.

**To Reproduce**
The relevant part of my nanomq.conf file looks like this:
```
auth {
    allow_anonymous = false
    no_match = deny
    deny_action = disconnect
    
    cache = {
        max_size = 32
        ttl = 1m
    }
    
    http_auth = {
        auth_req {
            url = "http://host.docker.internal:20080/mqtt/auth"
            method = "POST"
            headers.content-type = "application/x-www-form-urlencoded"
            params = {clientid = "%c", username = "%u", password = "%P"}
        }

        super_req {
            url = "http://host.docker.internal:20080/mqtt/superuser"
            method = "POST"
            headers.content-type = "application/x-www-form-urlencoded"
            params = {clientid = "%c", username = "%u", password = "%P"}
        }

        acl_req {
            url = "http://host.docker.internal:20080/mqtt/acl"
            method = "POST"
            headers.content-type = "application/x-www-form-urlencoded"
            params = {clientid = "%c", username = "%u", access = "%A", ipaddr = "%a", topic = "%t", mountpoint = "%m"}
        }

        timeout = 5s
        connect_timeout = 5s
        pool_size = 32
    }
}
```

**Environment Details**
 - NanoMQ version: v0.21.6-6
 - Operating system and version: Docker image from emqx/nanomq:latest
 - Compiler and language used: N/A

**Client SDK**
- MQTTX client from https://mqttx.app/
- Python paho.mqtt.client

**Additional context**
NanoMQ log is attached, but shows no warnings or errors.

[nanomq.log](https://github.com/nanomq/nanomq/files/14587455/nanomq.log)

**Comment by JaylinYu** [comment]
This is not implemented yet, has been requested several times though ....

**Comment by JaylinYu** [comment]
Sorry, that was on my plan long time ago, and I was thinking it will be implementated very soon. However god keeps throwing troubles to me. 🌝🌝

**Comment by zhijianfree** [comment]
@RanMaoyi   i have test nanomq 0.21.9 with docker,  it still can not receive acl_request

**Comment by RanMaoyi** [comment]
> @RanMaoyi i have test nanomq 0.21.9 with docker, it still can not receive acl_request

https://github.com/nanomq/nanomq/pull/1724

**Comment by JaylinYu** [comment]
Implemented and released
