### ISSUE TITLE
Users in pwd-file ignored

### ISSUE THREAD

**Issue by t0th0mas** [nanomq/nanomq#1716]
**Describe the bug**
Using /etc/nanomq_pwd.conf for storing username/password combinations.
1. If the password contains only numbers, the user is ignored
2. If the username contains one or more dots (.), the user is ignored.

**Expected behavior**
User/Password combination works as expected, even with only numbers in the password or dots in the username.

**Actual Behavior**
Users **test** and **test.test** are ignored.
```
2024-03-23 22:15:43 [823] INFO  /nanomq/nng/src/supplemental/nanolib/conf.c:978 print_auth_conf: [0] username: test1
2024-03-23 22:15:43 [823] INFO  /nanomq/nng/src/supplemental/nanolib/conf.c:978 print_auth_conf: [1] username: test2
```

**To Reproduce**
_/etc/nanomq_pwd.conf_
```
test1: ABCD
test: 12345
test2: ABCD
test.test: ABCD
```

**Environment Details**
 - NanoMQ v0.21.8-7
 - Docker image from official Docker Hub

**Comment by OdyWayne** [comment]
> If the password contains only numbers, the user is ignored

pure numbers in password is supported now. --> https://github.com/nanomq/NanoNNG/pull/906

> If the username contains one or more dots (.), the user is ignored.

dot is special character in parsing conf files, I recommend you not using dot in usernames or password for now. But we will consider whether we should support this.

**Comment by JaylinYu** [comment]
good suggestion, will plan to suppport it.

**Comment by OdyWayne** [comment]
you can use only numbers as following: 
```
"test1": "ABCD"
"test2": "ABCD"
"test": "12345"
```

**Comment by mehdi-song** [comment]
I use this configuration in nanomq.conf : 
`auth {
    allow_anonymous = false
    no_match = deny
    deny_action = ignore
    
    cache = {
        max_size = 32
        ttl = 1m
    }
    
     password = {include "/etc/nanomq_pwd.conf"}
    # acl = {include "/etc/nanomq_acl.conf"}
}`

And nanomq_pwd.conf:
`"client": "Qaz12345"`

but the topics stored in db.
