### ISSUE TITLE
Several possible memory leak defects.

### ISSUE THREAD

**Issue by LuMingYinDetect** [nanomq/nanomq#1719]
Hello! Today, I rechecked nanomq using the memory leak detection tool I developed and found several potential memory leak defects (there may be false positives). I conducted preliminary filtering of the error reports and uploaded the filtered reports of potentially genuine memory leak defects to the following link: https://gitee.com/yin-luming/nanomq_full_report.git. Please note that there are multiple HTML files in the repository, and one HTML file may contain reports for multiple defects (click on the Reports tab on the left side of the HTML page to switch views). When confirming, simply focus on defects labeled as memory leaks; almost all other types of defects are likely false positives. However, some memory leak types of defects may also be false positives. You only need to pull the repository to a Windows operating system and use a browser to view the reports.

**Comment by JaylinYu** [comment]
thanks for reporting potential issues
