### ISSUE TITLE
nanomq  Only one cpu can be used

### ISSUE THREAD

**Issue by HandsomeBoy01** [nanomq/nanomq#1731]
**Describe the bug**

 We ran nanomq in docker, connected 300 clients, and docker stats looked at cpu103%, whereas top-c view was only used 25%

**Expected behavior**
 Ability to use multiple cores
 

**To Reproduce**
If possible include actual reproduction test code here.
Minimal C test cases are perferred.

**Environment Details**
 - NanoMQ 0.21.8-full
 -  Linux nanomq 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by JaylinYu** [comment]
plz provide your config file. Have you set taskq and parallelism more than 1, if so then there is other limitation in your OS

**Comment by JaylinYu** [comment]
Better run it without docker to eliminate side effects.
