### ISSUE TITLE
infinite loop messages with bridges over tcp

### ISSUE THREAD

**Issue by amcharhal** [nanomq/nanomq#1733]
Hello, I'm not sure if this is a bug or a feature request.

I want to use bridges between 3 brokers. I'm using this forwards and subscriptions configuration:

Forwards:

Forwards: [    {        localTopic: "topic/#",        remoteTopic: "",        qos: 2    }] 

Subscriptions:[    {        localTopic: "",        remoteTopic: "topic/#",        qos: 2    }]

When I send a message on the topic "topic/myapp," for example from one of those servers,  it produces an infinite loop of messages between brokers.

Using EMQX and its specific configuration does not produce the same issue.

**Comment by JaylinYu** [comment]
Use MQTTV5 bridge， the no local flag solves issue
