### ISSUE TITLE
How to enable output log to file in .so shared library?

### ISSUE THREAD

**Issue by yutf** [nanomq/nanomq#1735]

**Comment by JaylinYu** [comment]
I guess you are from our BBS
If you start with broker_start_with_conf, then pass a conf object with log enabled. 
Or I am afraid you have to enable it by modifying the code.

**Comment by yutf** [comment]
I started by specifying the configuration file through the broker_start() function. As long as the "to" parameter in the configuration file contains the "file" option, it will crash and exit. After deleting the "file" option, it can start normally, but the log cannot be output to a file. Is it because this use is not allowed in the .so library?

**Comment by JaylinYu** [comment]
Feel free to reopen it if you got new question
