### ISSUE TITLE
Query params for /api/v4/clients having no effect?

### ISSUE THREAD

**Issue by lg-ecmind** [nanomq/nanomq#1737]
According to the documentation on https://nanomq.io/docs/en/latest/api/v4.html i tried to pass the **/api/v4/clients** Endpoint  one of the specified query params (in this example "clientid")

It seems to have no effect at all. For testing this i have connected 2 clients via MQTTX (logged in under the same username)

**curl -i --basic -u admin:public -X GET "http://localhost:8081/api/v4/clients"** (without specified clientid) returns the following 

```
{
   "code":0,
   "data":[
      {
         "client_id":"mqttx_8c438c5f",
         "username":"lukas",
         "keepalive":60,
         "conn_state":"connected",
         "clean_start":true,
         "proto_name":"MQTT",
         "proto_ver":5
      },
      {
         "client_id":"mqttx_1e5722d6",
         "username":"lukas",
         "keepalive":60,
         "conn_state":"connected",
         "clean_start":true,
         "proto_name":"MQTT",
         "proto_ver":5
      }
   ]
}

```

**curl -i --basic -u admin:public -X GET "http://localhost:8081/api/v4/clients?clientid=mqttx_8c438c5f"** (with specified clientid) produces the same result

```
{
   "code":0,
   "data":[
      {
         "client_id":"mqttx_8c438c5f",
         "username":"lukas",
         "keepalive":60,
         "conn_state":"connected",
         "clean_start":true,
         "proto_name":"MQTT",
         "proto_ver":5
      },
      {
         "client_id":"mqttx_1e5722d6",
         "username":"lukas",
         "keepalive":60,
         "conn_state":"connected",
         "clean_start":true,
         "proto_name":"MQTT",
         "proto_ver":5
      }
   ]
}
```

Same issue when trying to query by  "username" query param (tested this with two unique users)

**I assumed that the query params for /clients can be used to filter the returned client list? (by the specified conditions in the documentations) but in my case it really didnt affect the result at all**

Im using NanoMQ v0.21.6-6 on Manjaro

**Comment by OdyWayne** [comment]
You should use `GET /api/v4/clients/{clientid}`, in your case `curl -i --basic -u admin:public -X GET "http://localhost:8081/api/v4/clients/mqttx_8c438c5f"`. Please check our docs again, we have demonstrated it in section `Client`.

**Comment by lg-ecmind** [comment]
### Thanks for the fast response and your information!

I tested your suggestion and it worked flawlessly, Thank you! 

My first approach was to use what i interpreted as the "full" **/clients** implementation (with all the supported query parameters) to be able to query information about clients in great detail, that is why i refrained from using **/api/v4/clients/{clientid}** but as i stated the supplied query parameters (i tested **clientid**, **username** and **clean_start**) have no effect on the return of the **/clients** endpoint.

Is it generally not supported to query the **/clients** endpoint with all the supported conditions? If not i would suggest  adjusting the documentation in that regard to avoid confusion
