### ISSUE TITLE
mqtt broker_tls.c:488: NULL msg detected in send_cb

### ISSUE THREAD

**Issue by javasalondev** [nanomq/nanomq#1749]
![nanomq_log](https://github.com/nanomq/nanomq/assets/9456870/4fceffb6-a518-4ea0-9dd1-f4fc6a38a471)

version 0.21.8

nanomq broker 报mqtt broker_tls.c:488: NULL msg detected in send_cb后
客户端连接就会pub不上来消息，重新断开连接进行重连后又恢复，这个是什么原因。
send_cb是什么消息

**Comment by JaylinYu** [comment]
you are probably using our master branch, plz stick to release tag.

**Comment by javasalondev** [comment]
空消息能不能输出warn 日志就行，不做断开连接处理。这个是我们生产环境出现的，着急解决这个问题，今天能发布吗

**Comment by javasalondev** [comment]
是客户端发了个空消息到broker 这个意思吗

**Comment by JaylinYu** [comment]
必须断开，不作重连处理就是你现在遇到的问题。

**Comment by JaylinYu** [comment]
> 是客户端发了个空消息到broker 这个意思吗

不是，是回复ack时，tls传输层回应失败。最好能断开重连，也可以做个无视的恢复尝试，但就需要你来帮试试了。

**Comment by javasalondev** [comment]
能否临时帮忙打个docker镜像。

**Comment by JaylinYu** [comment]
> 能否临时帮忙打个docker镜像。

那只有正式版本或pre release才有，请自己尝试。用nanomq的84a2c和nanonng的 test_1749分支即可。
或采用断开连接的新版本，这是最正常和稳妥的操作，tls不一定能恢复了。
要稳定的连接请考虑MQTT Quic
