### ISSUE TITLE
ws crash

### ISSUE THREAD

**Issue by OdyWayne** [nanomq/nanomq#1752]
**Describe the bug**
mqtt ws crash

**To Reproduce**
this is the python code to reproduce (github do not support .py file upload)
[paho_ws_test.txt](https://github.com/nanomq/nanomq/files/15006884/paho_ws_test.txt)

**Client SDK**
paho python

**Comment by JaylinYu** [comment]
Nothing wrong here, at least on my machine with https://github.com/nanomq/nanomq/pull/1751. To me is still a CI problem.

**Comment by JaylinYu** [comment]
however broker fail to close the connection in such a circumstance shall be considered as a bug
