### ISSUE TITLE
Any documentation or example for how to use nanomq for websocket? I see nng library has some code for it.

### ISSUE THREAD

**Issue by JaylinYu** [nanomq/nanomq#176]
Any documentation or example for how to use nanomq for websocket? I see nng library has some code for it.

Thanks!

_Originally posted by @gaolaowai in https://github.com/nanomq/nanomq/issues/83#issuecomment-883633752_

**Comment by gaolaowai** [comment]
Bump. :smiley:

**Comment by JaylinYu** [comment]
> Bump.

Hi bro, sorry to keep you waiting, Now WebSocket is supported in the master branch. You can either start with "ws://0.0.0.0/8083/mqtt" or configure it via config file. Please check it out.
