### ISSUE TITLE
tlstran_pipe_qos_send_cb: NULL msg detected in send_cb

### ISSUE THREAD

**Issue by amcharhal** [nanomq/nanomq#1760]
I'm using TLS between my client and broker, and when sending a lot of messages using QoS 2, the client connection is closed with no explanation. In the server logs, I see this warning: 'tlstran_pipe_qos_send_cb: NULL message detected in send_cb'.
is that bug client side or server side

**Comment by amcharhal** [comment]
This bug bloc the broker, and no longer to publish any message.
I have to restart the server or deconnect clients

**Comment by JaylinYu** [comment]
not 1544, but highly similar to https://github.com/nanomq/nanomq/issues/1749, sorry for the Chinese words, basically he wants an auto-recovery from TLS transport failure, however I cannot test it on my place.

I have fixed this one in the pre-release 0.21.9. Would appreciate if anyone of you could have a try on the auto-recover version:  nanomq: 84a2c + nanonng:test_1749



> This bug causes the broker to become unresponsive, preventing it from publishing any messages. I need to restart the server or disconnect clients to resolve the issue
> 
> is it related to this bug ? #1544

**Comment by amcharhal** [comment]
Removing TLS, it's works fine. The same problem with bridges, using TLS and  qos 2.

**Comment by JaylinYu** [comment]
Yup, told u, try 0.21.9.

**Comment by amcharhal** [comment]
Are there any parameters, either on the client or server side, that can be configured to enable automatic recovery from TLS issues? I'm currently using the latest version 0.21.-10. When bridges with high message rates (1000ms/s) are in use, they sometimes block the process, and the connected brokers don't receive published messages. When this occurs, I have to manually restart the publisher broker. I'm not sure if this is a problem with my bridge configuration, but it works fine with a lower message rate. Do you have any documentation or examples on how to create a mesh network and establish fully connected brokers please

**Comment by amcharhal** [comment]
I use this configuration diagram to build bridges between three brokers. 
The goal is to establish a fully connected network. Could you please ta
![bridges](https://github.com/nanomq/nanomq/assets/24534036/7678a6e6-490b-4c94-af61-31781e18f896)
Take a look at the attached image for reference? I

**Comment by JaylinYu** [comment]
It is not your topology or bridging scenario that causes an issue. This is a bug as I stated before. 
And we shall close the TLS connection if transport doesn't behave correctly, no auto-recovery from NULL msg received.
However seems like you are talking about the blocking issue, then yes, it definitely should not happening in the first place, will publish a fix ver.

**Comment by JaylinYu** [comment]
feel free to reopen it if you have new question
