### ISSUE TITLE
High idle CPU usage with latest full docker image

### ISSUE THREAD

**Issue by codetronics** [nanomq/nanomq#1768]
**Describe the bug**
We noticed high idle CPU usage when the official docker image (nanomq:0.21.9-full) is used.

**Expected behavior**
The app should not consume much CPU at idle state.

**Actual Behavior**

```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
2722535157ae        nanomq              175.11%             752KiB / 998.2MiB   0.07%               3.98kB / 2.21kB     0B / 0B             13

```

```
top - 03:25:16 up  1:00,  0 users,  load average: 2.49, 2.67, 2.69
Tasks:   3 total,   2 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s):  8.8 us, 91.2 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :    998.2 total,    203.6 free,    246.9 used,    547.8 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.    735.9 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
    1 root      20   0  107000   2804   2468 R 174.7   0.3   7:04.56 nanomq
   28 root      20   0    4468   2040   1720 R   0.3   0.2   0:00.03 top
   19 root      20   0    2728   2172   1920 S   0.0   0.2   0:00.43 bash
```

**To Reproduce**

docker run -d -p 1883:1883 -p 8883:8883 --name nanomq emqx/nanomq:0.21.9-full

We just ran the above command. 

**Environment Details**
 - NanoMQ version: nanomq:0.21.9-full
 - Operating system and version:  Ubuntu 20.04 LTS (ARM 32-bit - Allwinner A20 SoC)

**Comment by JaylinYu** [comment]
Yes, it shouldn't, but this is not reproducible here. Could try 0.21.8 as well?

**Comment by codetronics** [comment]
We can close this issue as we discovered that the problem is because of the old docker engine (docker.io instead of docker-ce). The issue no longer occurring with the new engine.

Old engine: Docker version 19.03.8, build afacb8b7f0
Current engine: Docker version 26.1.1, build 4cf5afa

Thank you.

**Comment by JaylinYu** [comment]
Mysterious Docker...
