### ISSUE TITLE
Weird ASSERT warning in self-complied Docker?

### ISSUE THREAD

**Issue by pjh411589133** [nanomq/nanomq#1778]
**Describe the bug**

使用服务方式启动nanomq，
[Service]
Type=simple
ExecStart=/opt/wonen/nanomq/bin/nanomq start --conf etc/nanomq.conf
Restart=on-failure
RestartSec=20
StartLimitInterval=0

当桥接不断失败后，会自动重启，版本0.21.8  。期望桥接失败不影响本地继续使用
`
May 11 16:23:30 orangepi5 nanomq[5987]: 2024-05-11 16:23:30 [5994] WARN  /home/econe/dev/nanomq/nng/src/mqtt/protocol/mqtt/mqtt_client.c:747 mqtt_recv_cb: MQTT client recv error 136!
May 11 16:23:30 orangepi5 nanomq[5987]: 2024-05-11 16:23:30 [5993] WARN  /home/econe/dev/nanomq/nng/src/mqtt/protocol/mqtt/mqtt_client.c:699 mqtt_send_cb: MQTT client send error 7!
May 11 16:23:30 orangepi5 nanomq[5987]: 2024-05-11 16:23:30 [5994] ERROR /home/econe/dev/nanomq/nanomq/apps/broker.c:305 server_cb: RECV nng aio result error: 31 or NULL msg received
May 11 16:23:30 orangepi5 nanomq[5987]: 2024-05-11 16:23:30 [6006] WARN  /home/econe/dev/nanomq/nanomq/bridge.c:1081 bridge_tcp_disconnect_cb: bridge client disconnected! RC [139]
May 11 16:23:31 orangepi5 nanomq[5987]: 2024-05-11 16:23:31 [5998] WARN  /home/econe/dev/nanomq/nng/src/mqtt/protocol/mqtt/mqtt_client.c:747 mqtt_recv_cb: MQTT client recv error 136!
May 11 16:23:31 orangepi5 nanomq[5987]: panic: /home/econe/dev/nanomq/nng/src/mqtt/transport/tcp/mqtt_tcp.c: 807: assert err: len == nni_ms
May 11 16:23:31 orangepi5 nanomq[5987]: This message is indicative of a BUG.
May 11 16:23:31 orangepi5 nanomq[5987]: Report this at https://github.com/emqx/nanomq
May 11 16:23:31 orangepi5 nanomq[5987]: 2024-05-11 16:23:31 [5999] ERROR /home/econe/dev/nanomq/nanomq/apps/broker.c:104 sig_handler: signal signumber: 6 received!
May 11 16:23:31 orangepi5 systemd[1]: nanomq.service: Main process exited, code=exited, status=1/FAILURE
May 11 16:23:31 orangepi5 systemd[1]: nanomq.service: Failed with result 'exit-code'.
May 11 16:24:01 orangepi5 systemd[1]: nanomq.service: Scheduled restart job, restart counter is at 2.
May 11 16:24:01 orangepi5 systemd[1]: Stopped nanomq.
May 11 16:24:01 orangepi5 systemd[1]: Started nanomq.
May 11 16:24:01 orangepi5 nanomq[7372]: {}
May 11 16:24:01 orangepi5 nanomq[7372]: Server URL: mqtt-tcp://172.16.1.20:1883
May 11 16:24:01 orangepi5 nanomq[7372]: NanoMQ Broker is started successfully!
May 11 16:24:01 orangepi5 nanomq[7372]: 2024-05-11 16:24:01 [7377] WARN  /home/econe/dev/nanomq/nng/src/mqtt/protocol/mqtt/mqtt_client.c:747 mqtt_recv_cb: MQTT client recv error 136!
May 11 16:24:01 orangepi5 nanomq[7372]: 2024-05-11 16:24:01 [7377] ERROR /home/econe/dev/nanomq/nanomq/apps/broker.c:305 server_cb: RECV nng aio result error: 31 or NULL msg received
May 11 16:24:01 orangepi5 nanomq[7372]: 2024-05-11 16:24:01 [7377] ERROR /home/econe/dev/nanomq/nanomq/apps/broker.c:305 server_cb: RECV nng aio result error: 7 or NULL msg received
May 11 16:24:01 orangepi5 nanomq[7372]: 2024-05-11 16:24:01 [7393] WARN  /home/econe/dev/nanomq/nanomq/bridge.c:1081 bridge_tcp_disconnect_cb: bridge client disconnected! RC [139]
May 11 16:24:04 orangepi5 nanomq[7372]: 2024-05-11 16:24:04 [7386] WARN  /home/econe/dev/nanomq/nng/src/mqtt/protocol/mqtt/mqtt_client.c:747 mqtt_recv_cb: MQTT client recv error 136!

`

**Comment by JaylinYu** [comment]
Hi I cannot reproduce your error in my docker. and I also notice that you are running a self-build docker, have you changed any other code?

这个assert 是为了避免发出错误的畸形报文设置的，如果你修改了其他代码，可以删除这个NNI_ASSERT避免报警退出。但我检查了现在的桥接重连，并不会发出畸形的CONNECT。 
下个版本我也会把ASSERT修改成log_error

**Comment by pjh411589133** [comment]
Yes, I've made some changes to the bridging code. My C programming skills are just beginner level, so please don't laugh。
I compiled and ran it on ARM


改动源码代码的文件
nanomq/apps/broker.c
nanomq/bridge.c
nanomq/include/bridge.h
nng/include/nng/nng.h
nng/src/supplemental/mqtt/mqtt_public.c
nng/src/supplemental/mqtt/mqtt_qos_db.c
nng/src/supplemental/mqtt/mqtt_qos_db.h






潘健洪
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "nanomq/nanomq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月13日(星期一) 晚上7:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nanomq/nanomq] Weird ASSERT warning in self-complied Docker? (Issue #1778)





 
Hi I cannot reproduce your error in my docker. and I also notice that you are running a self-build docker, have you changed any other code?
 
这个assert 是为了避免发出错误的畸形报文设置的，如果你修改了其他代码，可以删除这个NNI_ASSERT避免报警退出。但我检查了现在的桥接重连，并不会发出畸形的CONNECT。
 下个版本我也会把ASSERT修改成log_error

**Comment by JaylinYu** [comment]
Sorry I Cannot help you base on the information you provide. 
Please contact EMQ or my email if you need commercial support of self-defined development
