### ISSUE TITLE
如果客户端执行unsubscribe 服务端就会segmentation fault

### ISSUE THREAD

**Issue by carl9881** [nanomq/nanomq#178]
下载的是 master 分支的最新代码.  

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff31c2700 (LWP 19608)]
0x0000000000417fc1 in del_topic_one ()
Missing separate debuginfos, use: debuginfo-install libatomic-4.8.5-44.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64
(gdb) bt
#0  0x0000000000417fc1 in del_topic_one ()
#1  0x0000000000416505 in unsub_ctx_handle ()
#2  0x00000000004225a3 in server_cb ()
#3  0x00000000004343bd in nni_taskq_thread ()
#4  0x0000000000434dc2 in nni_thr_wrap ()
#5  0x0000000000438292 in nni_plat_thr_main ()
#6  0x00007ffff7bc6163 in start_thread (arg=0x7ffff31c2700) at pthread_create.c:309
#7  0x00007ffff6ab0f6d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by JaylinYu** [comment]
多谢！
