### ISSUE TITLE
NanoMQ accidentally send Reserved-type packets to clients

### ISSUE THREAD

**Issue by songxpu** [nanomq/nanomq#1780]
**Describe the bug**

When we send a CONNECT packet (MQTT version 3.1) that carries the will topic to NanoMQ, NanoMQ saves such a will message; when a subsequent client initiates a normal subscription to the will topic, NanoMQ accidentally forwards the will message to the client, and it is still of the Reserved type, which violates two rules:

1. The broker can only send a will message on the corresponding topic if the subscribing client disconnects unexpectedly
2. Reserved messages are prohibited.

**To Reproduce**

First, send the Connect packet
```
echo 103d00064d51497364700376225e0003675977000146000c5141674e586e367750775051001949764873317a50305355644d6842777a7254486747644d4d4b | xxd -p -r | nc 172.17.0.6 1883
```
Then, send the Connect and Subscribe Packet
```
echo 107300064d514973647003d49498001432764656424f365950574739704650435463565a00076b724a5448616c000b787a5353526f444bff44430019664f4739766c306a77595165793057586346364576315a4a6e001e383952707861723265476d793635444d69745478764f754c6f58595a7a308217d08e000434586c79000001460000074b58597530484501 | xxd -p -r | nc 172.17.0.6 1883
```
![image](https://github.com/nanomq/nanomq/assets/44093631/3899da1f-8ae5-4425-8308-e2df00642b08)

**Environment Details**
 - NanoMQ 0.21.8

**Client SDK**
If possible include the mqtt sdk you used to connect to nanomq
Minimal C test cases are perferred.

**Additional context**

**Comment by JaylinYu** [comment]
Thank for reporting, but it is not reproducible here. The broker only replied CONNACK and SUBACK in my test, and I did exactly as you suggested.
![Screenshot from 2024-05-14 11-43-31](https://github.com/nanomq/nanomq/assets/64823539/3cf51be1-cf85-4bd2-aa2a-409496f28379)


But I see there is a retain msg going on, so I suspect you are hitting the issue https://github.com/nanomq/nanomq/issues/1769
plz verify your case after this fix, and provide your conf file if you feel it is necessary

**Comment by JaylinYu** [comment]
> Hi @JaylinYu I also encountered your situation during retesting, and I found out that the steps of sending packets can have an impact on the results.
> 
> In my testing, I first restarted NanoMQ with the default configuration file: `nanomq start`
> 
> Then send the first packet, and then close this connection. ![image](https://private-user-images.githubusercontent.com/44093631/330275077-4f451461-0f3d-4770-9829-0e60b90f7e8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjQxMzUsIm5iZiI6MTcxNTY2MzgzNSwicGF0aCI6Ii80NDA5MzYzMS8zMzAyNzUwNzctNGY0NTE0NjEtMGYzZC00NzcwLTk4MjktMGU2MGI5MGY3ZThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA1MTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNzk5NTYxYjZmYTg5YjNlNjQ4ZmFkNzU3Y2M2YzJhNGM0MDIzYTBmOGMyZDQyZGM2ZmQ4NDkxZWViZWViMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q4CHB-hCKd5p6uRToO1HTeIvCVKIJsZgu3u8I8UZ890)
> 
> Next, send the second packet. ![image](https://private-user-images.githubusercontent.com/44093631/330275107-6fdbc4cb-d51e-4144-adef-e8f1b8545560.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjQxMzUsIm5iZiI6MTcxNTY2MzgzNSwicGF0aCI6Ii80NDA5MzYzMS8zMzAyNzUxMDctNmZkYmM0Y2ItZDUxZS00MTQ0LWFkZWYtZThmMWI4NTQ1NTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA1MTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NzQ5YjgxOGQ0MWE3MTU4OWNkNTA5YTQ2MmQwYmI1MzcxZWJmYmJhMjg4MjY1NmI4NmI4OWExNzc4ZTRmMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZkdRyfFVojighnDx_xUSUat3AfbOCcXzsbAGrIou2Y4)
> 
> By following the above steps, I am able to stably reproduce this issue in my environment ![image](https://private-user-images.githubusercontent.com/44093631/330274978-0023e653-e301-4d67-b4a6-ddd9f0b26451.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjQxMzUsIm5iZiI6MTcxNTY2MzgzNSwicGF0aCI6Ii80NDA5MzYzMS8zMzAyNzQ5NzgtMDAyM2U2NTMtZTMwMS00ZDY3LWI0YTYtZGRkOWYwYjI2NDUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA1MTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YTUxOWRlNzI2MGIwN2YzODQwZDY3OTRiYjE3ZjE5NDQ0YzdjM2E0NTJmMDhhNTQ4OGZiZWI1YzUyMDc1ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cb1l0tjo7TXr78suH_n8YeCjrX8gatiVpYL3vZ6T16Y)

Nothing different if I disconnect first client first, what i see is just a retain msg.
perhaps you could try binary instead of docker.

**Comment by JaylinYu** [comment]
Ok forget about docker, I misread your words.
Anyway, something else is definitely interfering with the nanomq to cause this behavior. Perhaps the retain message in SQLite, network error, or something else. I don't know. 
This case is simply not happening again. I am not saying it is a false report; The root reason might be sth else, and I just need more clues to reproduce it.

**Comment by JaylinYu** [comment]
As you can see,we put fuzzing dataset to our CI, and it passed.
