### ISSUE TITLE
How to preserve retain flag in bridging?

### ISSUE THREAD

**Issue by pjh411589133** [nanomq/nanomq#1790]
**Describe the bug**

我使用了retain持久化配置
sqlite {
    disk_cache_size = 102400
    mounted_file_path = "/usr/local/etc/"
    flush_mem_threshold = 100
    resend_interval = 5000
}

使用桥接功能，当从emqx发送 retain 消息桥接到nanomq
Topic: /node/ad345be3b320d/t123QoS: 0
{"msg": "ret111"}

Topic: /node/ad345be3b320d/t123QoS: 0
{"msg": "ret222"}

Topic: /node/ad345be3b320d/t123QoS: 0
{"msg": "ret333"}

nanomq的客户端连接后都是拿到消息：{"msg": "ret111"}  只有重启nanomq，nanomq的客户端连接后才能拿到消息{"msg": "ret333"}

**Comment by JaylinYu** [comment]
This is not nanomq's fault. EMQX will treat new retain msg you pub as a common publish msg, the only way to get this remain update  in MQTT 3.1.1 is re-sub, or use MQTT5, rap & rh

**Comment by pjh411589133** [comment]
能否明确，桥接和客户端该怎么配置，已经测试好多次都不行，心态炸了
subscription = [ 
    {
      remote_topic = "cmd/topic1"
      local_topic = "topic3"
      qos = 1
      retain = ?
retain_as_publish = ?
retain_handling = ?
    }

MQTTX
retain_as_publish = ?
retain_handling = ?
![image](https://github.com/nanomq/nanomq/assets/38654872/023fd214-6bb0-4c34-8832-789d68db65b2)

**Comment by JaylinYu** [comment]
have a try on https://github.com/nanomq/NanoNNG/pull/1007?
