### ISSUE TITLE
Using conf file `listeners.tcp.*`'s port is ignored?

### ISSUE THREAD

**Issue by Mis1eader-dev** [nanomq/nanomq#1794]
**Describe the bug**
When using a conf file with the listener port set to anything, it is ignored and still uses 1883.

**Expected behavior**
Must use that file's listener port.

**Actual Behavior**
Ignores the set port.

**To Reproduce**
1. Using master branch, compile it with `cmake . -B ./build -G Ninja && ninja -C ./build`
2. Go to ./build/nanomq
3. Create `nanomq.conf` file with the content:
```conf
listeners.tcp.mqtt {
	bind = "0.0.0.0:11883"
}
```
4. Run with `./nanomq start --conf ./nanomq.conf`
5. Use the CLI or an MQTT client and connect to `mqtt://127.0.0.1:1883`, it succeeds
6. Now try connecting to `mqtt://127.0.0.1:11883`, it fails

**Environment Details**
 - NanoMQ version: 0.21.10
 - Operating system and version: Ubuntu 22.04.4 LTS
 - Compiler and language used: gcc, C
 - testing scenario: via terminal

**Client SDK**
MQTTX

**Additional context**
Setting the url manually works `./nanomq start --url nmq-tcp://0.0.0.0:11883`, but it specifically only works with "nmq-tcp" protocol, not with "mqtt-tcp". I assume the latter is just not an option.

**Comment by OdyWayne** [comment]
Please use the syntax we use in our example conf like
```
listeners.tcp {
	bind = "0.0.0.0:11883"
}
```
