### ISSUE TITLE
org.eclipse.paho.mqttv5.client 

### ISSUE THREAD

**Issue by jinyuttt** [nanomq/nanomq#1807]
Using org. eclipse. paho. mqttv5. client exception, connection returned error code 130.
windows11
nanomq-0.21.10-windows-x86_64

**Comment by OdyWayne** [comment]
That's more likely an issue from the client side, make sure the client side works fine. And we may need more context to understand  your issue.

**Comment by jinyuttt** [comment]
![image](https://github.com/nanomq/nanomq/assets/13539621/c8ade044-f3bc-49ac-b3fd-0e6b603f2833)

**Comment by JaylinYu** [comment]
any nanomq log? 
possible due to unaligned protocol

**Comment by jinyuttt** [comment]
[nanomq.log](https://github.com/user-attachments/files/15598356/nanomq.log)

**Comment by OdyWayne** [comment]
> [nanomq.log](https://github.com/user-attachments/files/15598356/nanomq.log)

No much valuable information here, we need more detailed logs. And please make sure your client works fine. For example, testing with EMQX under the same conditions.
