### ISSUE TITLE
TLS 1.3

### ISSUE THREAD

**Issue by MathiasLopes** [nanomq/nanomq#1815]
I need to use TLS 1.3. In fact, when I enable TLS, I can't limit it to TLS 1.3.
Is this currently possible?
I haven't seen an option to do this yet in the documentation.

**Comment by JaylinYu** [comment]
NanoMQ relies on MbedTls for TLS support.

**Comment by MathiasLopes** [comment]
@JaylinYu Have we any documentation about how to plug it with NanoMQ ?

**Comment by JaylinYu** [comment]
Now we have updated the MbedTLS ver, you canuse TLS1.3 in the next release

**Comment by JaylinYu** [comment]
Maybe too late for @MathiasLopes , but still would be benefit to late comers
mbedtls dependency of the system defines the behaviour of NAnoMQ TLS, if you want to limit to 1.3, you may need to modify the code here 

`cfg->min_ver = MBEDTLS_SSL_MINOR_VERSION_4;` in tls.c line 474
