### ISSUE TITLE
http acl unsuccessful

### ISSUE THREAD

**Issue by longjiaojiaolong** [nanomq/nanomq#1818]
Revise

<img width="839" alt="Snipaste_2024-06-30_17-26-07" src="https://github.com/nanomq/nanomq/assets/164883806/29a184a4-68d3-48ee-964b-5aaae81d9fcf">

TO

<img width="720" alt="Snipaste_2024-06-30_17-26-52" src="https://github.com/nanomq/nanomq/assets/164883806/9fd62fb0-9a20-4379-8134-7f66a9bd4152">

**Comment by RanMaoyi** [comment]
Thanks for your feedback, and feel sorry for negligence, fix is on the way https://github.com/nanomq/NanoNNG/pull/1003
