### ISSUE TITLE
When connecting using the websocket protocol, if the username or password is empty, it will crash.

### ISSUE THREAD

**Issue by morningf** [nanomq/nanomq#1819]
**Describe the bug**
When connecting using the websocket protocol, if the username or password is empty, it will crash.

**To Reproduce**
Use any MQTT client at will (such as MQTTX), connect using the WebSocket protocol, set the username and password to empty, and then make the connection. The broker will crash.

** Environment Details **
 - NanoMQ 0.21.10
 - Windows 11

**Comment by JaylinYu** [comment]
Yup, nanomq crashed while kicking this client. Will fix it soon.
But the root cause is that MQTTX is sending a malformed utf8 username, which is considered as protocol error
