### ISSUE TITLE
nanomq reload command failed

### ISSUE THREAD

**Issue by thomascenni** [nanomq/nanomq#1829]
**Describe the bug**
Configuration is not reloaded.

**Expected behavior**
Reload of the configuration.

**Actual Behavior**
Got message "reload failed!"

**To Reproduce**
Just run:
``
nanomq reload
``
without any configuration change.

**Environment Details**
 - NanoMQ version: official Docker version v0.22.1-3
<img width="1179" alt="Screenshot 2024-07-07 at 11 08 09" src="https://github.com/nanomq/nanomq/assets/33039107/5131c586-bedf-4b7c-b103-83bc80fd29f6">

**Comment by jmmk** [comment]
I'm not sure if it's the intended behavior, but I notice I have to pass `--conf` to get `reload` to success.

Example:

```shell
nanomq reload # fails
nanomq reload --conf /etc/nanomq.conf # succeeds
```

**Comment by JaylinYu** [comment]
I believe you guys have found the way....

**Comment by thomascenni** [comment]
Hello @JaylinYu 
Which parameters are reloaded ? I am interested in reloading SQLite rules, and I don't see any other way because of a bug on the CLI rules (see https://github.com/nanomq/nanomq/issues/1828).
Thanks

**Comment by OdyWayne** [comment]
[This](https://nanomq.io/docs/en/latest/toolkit/command-line.html) is how `reload` is used. We may need more detailed error logs here.

**Comment by JaylinYu** [comment]
reload of Rule engines is not supported yet
