### ISSUE TITLE
 msg lost

### ISSUE THREAD

**Issue by jonasfoyth** [nanomq/nanomq#1832]
Hello! I'm testing nanomq on some devices and I came across a specific error:

`bridge_handler: bridging to tls+mqtt-tcp://broker.xx.xx.io:8883 aio busy! msg lost! Ctx: 1
`

On other devices, i'm using Mosquitto with the max_inflight_messages option, due to a server limitation (1 msg/s/topic) is there any way to currently limit this?

[nanomq-log.txt](https://github.com/user-attachments/files/16167885/nanomq-log.txt)

config:
```
system {
    num_taskq_thread = 0  # Use a specified number of task queue threads
    max_taskq_thread = 0  # Use a specified maximum number of task queue threads
    parallel = 0          # Handle a specified maximum number of outstanding requests
}

mqtt {
    property_size = 32
    max_packet_size = 512KB
    max_mqueue_len = 2048
    retry_interval = 5s
    keepalive_multiplier = 1.25   
    #max_inflight_window tested but not working yet
}

listeners.tcp {
    bind = "127.0.0.1:1883"
}

listeners.ws {
    bind = "127.0.0.1:8083/mqtt"
}

sqlite {
  disk_cache_size = 102400
  mounted_file_path="/data/nanomq/"
  flush_mem_threshold = 1000
  resend_interval = 5000
}

auth {
    allow_anonymous = true # Allow clients to connect without providing username/passwor d
    no_match = allow       # Default action if no ACL rules mat
    deny_action = ignore   # Action to take if an ACL check rejects an operationi
    cache = {
	max_size = 32        # Maximum number of ACL entries to cache for a client
        ttl = 1m             # Time after which an ACL cache entry will be delete
    }
	
    #password = {include "/etc/nanomq_pwd.conf"} # Path to the password configuration file
    #acl = {include "/etc/nanomq_acl.conf"}       # Path to the ACL configuration file
}

log {
    to = [file, console]
    level = debug
    dir = "/data/nanomq"
    file = "nanomq.log"
    rotation {
        size = 10MB
        count = 2
    }
}


bridges.mqtt.test = {
 # server = "tls+mqtt-tcp://broker.emqx.io:8883"    # MQTT server address
  server = "tls+mqtt-tcp://broker.xxxx:8883"
  proto_ver = 4                          # MQTT protocol version
  clientid = "xxx"   # Client ID for the bridge
  keepalive = "60s"                       # Ping interval for the bridge
  clean_start = false                     # Clean start flag for the bridge
  username = "xx"                   # Username for the bridge
  password = "xxx"                     # Password for the bridge
  ssl = { 

     keyfile = "/etc/ssl/certs/" 
     certfile = "/etc/ssl/certs/"
     cacertfile = "/etc/nanomq/xxx"
  }
forwards = [
        {
	        remote_topic = ""
	        local_topic = "server/+/state"
	        qos = 1
        },
        {
	        remote_topic = ""
	        local_topic = "server/+/toAgent/flows"
	        qos = 1
        },
        {
	        remote_topic = ""
	        local_topic = "server/+/fromAgent/+"
	        qos = 1
        },
        {
	        remote_topic = ""
	        local_topic = "server/+/fromAgent/hello"
	        qos = 1
        },
        {
	        remote_topic = ""
	        local_topic = "server/+/fromAgent/debug"
	        qos = 1
        },
        {
	        remote_topic = ""
	        local_topic = "server/+/fromAgent/flowStats"
	        qos = 1
        },
        {
	        remote_topic = ""
	        local_topic = "application/ios-api/#"
	        qos = 1
        },
        {
	        remote_topic = ""
	        local_topic = "application/modbus-api/#"
	        qos = 1
        },
        {
	        remote_topic = ""
	        local_topic = "server/+/fromAgent/hello"
	        qos = 1
        }
]

subscription = [
        {
	        remote_topic = "server/+/command"
	        local_topic = ""
	        qos = 1
        },
        {
	        remote_topic = "server/+/toAgent/flows"
	        local_topic = ""
	        qos = 1
        },
        {
	        remote_topic = "server/+/toAgent/peripherals"
	        local_topic = ""
	        qos = 1
        },
        {
	        remote_topic = "server/+/toAgent/debug"
	        local_topic = ""
	        qos = 1
        },
        {
	        remote_topic = "server/+/toAgent/+"
	        local_topic = ""
	        qos = 1
        },
        {
	        remote_topic = "server/+/toAgent/virtualButton"
	        local_topic = ""
	        qos = 1
        },
        {
	        remote_topic = "modbus-api/#"
	        local_topic = ""
	        qos = 1
        },
        {
	        remote_topic = "ios-api/#"
	        local_topic = ""
	        qos = 1
        }
]


  max_parallel_processes = 2              # Maximum number of parallel processes for handling outstanding requests
  max_send_queue_len = 1024               # Maximum number of message send queue length
  max_recv_queue_len = 1024               # Maximum number of message receive queue length
}

bridges.mqtt.cache {
    disk_cache_size = 102400   # Max message limitation for caching
    mounted_file_path = "/data/nanomq/"  # Mounted file path 
    flush_mem_threshold = 200  # The threshold of flushing messages to flash
    resend_interval = 5000 # The interval of resending cached SQLite msg
}
```

**Environment Details**
 - NanoMQ version: 0.22.1-r0
 - Operating system and version: custom build (yocto)
 - testing scenario: Nanomq with local and bridge + tls (all options working) - device with 1 core (1Ggz) + 100mb ram

**Comment by JaylinYu** [comment]
is that "tls+mqtt-tcp://broker.xxxx:8883" a mosquitto instance with inflow msg rate limitation (1 msg/topic/s) as you said?
If so, you could set your own "parallel" number to increase the cache ctx limit, however, it just gives more space to cache the msgs that mosquitto cannot keep up with, still gonna drop msg when that space is used up.

**Comment by JaylinYu** [comment]
is that "tls+mqtt-tcp://broker.xxxx:8883" a mosquitto instance with inflow msg rate limitation (1 msg/topic/s) as you said?
If so, you could set your own "parallel" number to increase the cache ctx limit, however, it just gives more space to cache the msgs that mosquitto cannot keep up with, still gonna drop msg when that space is used up.

**Comment by jonasfoyth** [comment]
Explaining better, I have two devices running, one with Mosquitto and the other with Nanomq. On the device with mosquitto I use the max_inflight_messages option to limit messages according to the server requirement (1 msg/s/topic). 

Increasing the "parallel" option makes the error more recurring, new log: 
[nanomq-log2.txt](https://github.com/user-attachments/files/16175659/nanomq-log2.txt)

**Comment by JaylinYu** [comment]
as simple as I said, it is the remote broker cannot keep up with bridging, reply ACK too slow due to whatever reason.
Either increase the performance of remote broker, or switch to QoS 0, or keep increasing parallel number. Mosquitto is a single thread arch, as a huge loop, which canot reach same parallism as nanomq, thats why you dont see similiar behaviour.
what else do you expect then? Limit nano to slow down the inflowing msg?

**Comment by JaylinYu** [comment]
max_inflight_window is just an independent ack queue for QoS msg, which differs it with max_mqueue_len. In other words, it is just similar to mosquitto's `max_inflight_messages`.

Yes,  it's pretty common to limit application resource for embedded device, that's why nanomq has similliar settings like parallel/queue_len/taskq.
by reducing `max_inflight_messages`, the msg wont be sync on bridging at same inflowing pace, mosquitto drops msg at first place, or shifts the burden to kernel itself (single thread limit), which doesn't seems right to me.
 Hence in your case, it is your publishing client's job to implement rate limit, It is not fair to ask nanomq for this. broker shall always reads socket at its best,

**Comment by JaylinYu** [comment]
now a new caching layer is added to take effects while TCP connection is closed
