### ISSUE TITLE
self-compiled  nanomq.exe on windows crash and exit

### ISSUE THREAD

**Issue by dwlhi** [nanomq/nanomq#1833]
I compile the nanomq source code on windows using cmake3.30.0，and I run the nanomq using follow command:
nanomq.exe start --conf config/nanomq.conf （allow_anonymous = false）

when I connect to the nanomq using a Mqttclient tool with wrong password , the nanomq.exe crash and quit，
Is my compile has some questions?

**Comment by dwlhi** [comment]
I compiled using vs2019.

**Comment by OdyWayne** [comment]
You can refer to our official [tutorial](https://www.emqx.com/en/blog/install-mqtt-broker-on-windows) for how to compile in Windows.

**Comment by JaylinYu** [comment]
Tried with the official windows release, nothing is wrong.

BTW, There was a bug in MQTT  over websocket, idk if you just hit that.
