### ISSUE TITLE
When cross compiling the nanomq.conf is installed in /etc on the host which doesn't make sense.

### ISSUE THREAD

**Issue by billpriest** [nanomq/nanomq#1872]
**Is your feature request related to a problem? Please describe.**
When cross compiling nanomq the nanomq is installed (or attempted to be installed) in /etc on the host.  Other packages when cross compiled install them in a CMAKE_INSTALL_PREFIX relative path.

**Describe the solution you'd like**
for nanomq.conf to be installed relative to the CMAKE_INSTALL_PREFIX if cross compiling. I modified CMakeLists.txt to do this as follows:
CMakeLists.txt
============
if (NOT WIN32 AND NOT CYGWIN)
  if (CMAKE_CROSSCOMPILING)
    install(FILES ${CONFIG_FILES}  DESTINATION ${CMAKE_INSTALL_PREFIX}/etc)
  else ()
    install(FILES ${CONFIG_FILES}  DESTINATION /etc)
  endif ()
else ()
  install(FILES ${CONFIG_FILES}  DESTINATION config)
  install(FILES libwinpthread-1.dll DESTINATION bin)
endif ()

**Describe alternatives you've considered**
A config file destination CMake variable could be created where the destination could be specified on the cmake command line.  I am admittedly a rank amature CMake user and needed a quick solution.

**Additional context**

**Comment by JaylinYu** [comment]
Cool, understood. Feel free to change it
