### ISSUE TITLE
Cannot forward message of size 0

### ISSUE THREAD

**Issue by rty813** [nanomq/nanomq#1880]
**Describe the bug**
When the forwarded message size is 0, an error will be reported and the message cannot be sent.

**Expected behavior**
Message which size is 0 can be sent.

**Actual Behavior**
```
2024-08-29 11:15:54 [13611] ERROR /home/runner/work/nanomq/nanomq/nng/src/platform/posix/posix_alloc.c:24 nni_alloc: malloc failed sz: 0

2024-08-29 11:15:54 [13611] ERROR /home/runner/work/nanomq/nanomq/nng/src/mqtt/protocol/mqtt/mqtt_client.c:1254 mqtt_ctx_send: MQTT client encoding msg failed2!
```

**To Reproduce**
nanomsg.conf:
```
forwards = [
		{
			remote_topic = "fwd/topic1"
			local_topic = "topic1"
			qos = 1
		},
]
```

then execute:
`mqttx pub -h 127.0.0.1 -p 1883 -t topic1 -m ""`

**Environment Details**
 - NanoMQ version
 `NanoMQ Messaging Engine for Edge Computing & Messaging bus v0.22.7-8`
 - Operating system and version
 `Ubuntu 18.04`

**Comment by JaylinYu** [comment]
Why do you need to send a zero size msg?
I prefer to leave it as it is now.

**Comment by rty813** [comment]
First of all, the mqtt protocol itself supports messages of size 0. I think nanomq should follow the mqtt protocol.
I send messages of size 0 as heartbeats

**Comment by JaylinYu** [comment]
Ok fine, will allow it in next 0.22.10 release
