### ISSUE TITLE
Does the configuration file support the use of environment variables?

### ISSUE THREAD

**Issue by rty813** [nanomq/nanomq#1881]
I want to use system environment variables in the configuration file

**Comment by rty813** [comment]
Or, how can nanomq automatically subscribe to the corresponding topic from the bridge when the local client subscribes to the topic?

**Comment by JaylinYu** [comment]
probably this is what you request

https://github.com/nanomq/nanomq/pull/1846

**Comment by rty813** [comment]
> probably this is what you request
> 
> #1846

Yes, that's what I needed, thank you so much

**Comment by rty813** [comment]
@JaylinYu I still need to use environment variables like $hostname in the configuration file. How can this be achieved?

**Comment by JaylinYu** [comment]
If I get you right. Do You want to use a placeholder in any configuration field?
Or you just ask when will that PR be merged?

**Comment by rty813** [comment]
> Do You want to use a placeholder like $hostname in any configuration field?

Yes，I want to add $hostname as part of the client_id.

**Comment by JaylinYu** [comment]
Currently, it is not available. and that would require code development in `conf_ver2.c`.

**Comment by rty813** [comment]
Are there any plans to support this in the future?

**Comment by JaylinYu** [comment]
It is not a generalized requirement to define a particular env params list. We only provide such a service to commercial customers.
But you can try your own customization.
