### ISSUE TITLE
enable session data store 

### ISSUE THREAD

**Issue by zsr228** [nanomq/nanomq#1885]
File: [/docs/zh_CN/config-description/broker.md](https://nanomq.io/docs/zh/latest/config-description/broker.html)

cannot find conf to set session data

**Comment by JaylinYu** [comment]
not quite get what you mean.
Are you looking for the sqlite config section?

**Comment by zsr228** [comment]
I means nanomq wether can store client session when client reconnect

**Comment by zsr228** [comment]
> not quite get what you mean. Are you looking for the sqlite config section?
> 
> nanomq will store retain + inflight + qos msg in sqlite if you enabling sqlite cache

I means nanomq wether can store client session when client reconnect

**Comment by zsr228** [comment]
> session keeping is a feature of MQTT, It is enabled by default.

I use this client set session true,previous subscribe lost when client reconnect

**Comment by JaylinYu** [comment]
Whoops, this is indeed a regression bug... I accidentally break it... 

It has been fixed , thanks for reporting!!!
