### ISSUE TITLE
docker image doesn't work properly

### ISSUE THREAD

**Issue by ZodiacWind** [nanomq/nanomq#189]
Use Command:

docker pull nanomq/nanomq:0.4.3

docker run --name nanomq nanomq/nanomq:0.4.3

Error Message:

"nanomq.conf ./etc/nanomq.conf" file not found or unreadable

**Comment by JaylinYu** [comment]
Hi zodiac, 
you can ignore the error message. it only tells you that nanomq couldn't find the self-defined conf file.
the docker image runs just fine. don't forget to map the port by "-p 1883:1883".

**Comment by ZodiacWind** [comment]
Fine, got it. Thank you.
