### ISSUE TITLE
Docker images "latest" tag

### ISSUE THREAD

**Issue by sprat** [nanomq/nanomq#1892]
**Is your feature request related to a problem? Please describe.**

For each release, there are different docker image flavors, e.g. "0.22.8", "0.22.8-full", "0.22.8-slim". However, this is not the case for the "latest" tag: I would love to have "latest", "latest-full", "latest-slim". Currently, it seems that the latest tag points to the slim version, but I would like to get the alpine version instead, because it's smaller.

**Describe the solution you'd like**

Just tag the different flavors with a latest prefix additionally to the version tag.

**Describe alternatives you've considered**

I have to use fixed version tags, so my container does not update automatically.

**Additional context**

None

**Comment by sprat** [comment]
Thanks !

**Comment by sprat** [comment]
Oh, there's still a problem, the "latest" image is the same image as the "latest-slim" currently.

**Comment by JaylinYu** [comment]
Also make it as your wish: https://github.com/nanomq/nanomq/pull/1896
but you need to wait for next release

**Comment by sprat** [comment]
I reacted because the new tags appeared on Docker Hub, but not as expected. But ok, fine, i will check the next release! Thanks.

**Comment by JaylinYu** [comment]
Nevermind， you are always welcome
