### ISSUE TITLE
The actual client disconnection time is longer than 1.5 times of keepalive

### ISSUE THREAD

**Issue by rty813** [nanomq/nanomq#1897]
**Describe the bug**
Theoretically, nanomq should consider the client disconnected when the client no longer sends any packets for 1.5 times the keepalive time. I set the client's keepalive to 5s. After disconnection, it will not disappear from the list queried through the api/v4/clients interface until 20s later.

**Expected behavior**
After 7.5s, the api/v4/clients interface cannot find the client

**Actual Behavior**
20s

**Environment Details**
 - NanoMQ version
   0.22
 - Operating system and version
   Ubuntu22.04

**Addition**
![image](https://github.com/user-attachments/assets/ae509880-8507-43a6-8718-bf2fa872d49a)

![image](https://github.com/user-attachments/assets/4f24ff30-52e7-4090-bb05-dbbd210a5bd2)

**Comment by rty813** [comment]
I can be sure that the client is disconnected because I just unplugged the network cable.

**Comment by JaylinYu** [comment]
You spot sth interesting.
There is a global timer controller: `retry_interval = 10s`
https://nanomq.io/docs/en/latest/config-description/mqtt.html#example-configuration

Which is to set the granularity of all periodical checkers. It also affects the resend interval and session expiry interval. You shall set it to 1s if you want a more sensitive nanomq. But be careful. It would consume more CPU when there are massive amounts of clients.

**Comment by rty813** [comment]
However, the parameter is annotated in the documentation as: `Retry interval for QoS 1/2 message delivering`，But in fact, this parameter will also affect other functions. It is recommended to add additional explanation to the document.
