### ISSUE TITLE
Data bridge forwarding setup

### ISSUE THREAD

**Issue by KarlG-03** [nanomq/nanomq#1908]
### Discussed in https://github.com/nanomq/nanomq/discussions/1907

<div type='discussions-op-text'>

<sup>Originally posted by **KarlG-03** September 19, 2024</sup>
Hi, I'm unable to connect to server, here's my setup
```
bridges.mqtt.emqx_bridge {
    server = "tls+mqtt-tcp://server:8883" 
    clientid = "nanomq_bridge_client-rand123123367"
    ssl = {
        cacertfile = "/etc/certs/cacert.pem"
    }
    proto_ver = 5
    keepalive = 60s
    clean_start = true
    username = "user"
    password = "pass"
    forwards = [
        {
            remote_topic = "/forward/event"
            local_topic = "test/topic"
            qos = 1
        }
    ]
    subscription = [
        {
            remote_topic = "/sub/event"
            local_topic = "test/topic"
            qos = 1
        }
    ]
}
```

and I'm getting `ERROR /nanomq/nanomq/bridge.c:1213 bridge_tcp_client: nng_dialer_create failed 9`

But I'm able to connect to the server using mqttx with this setup. with
`mqtts://server:8883`
with ca.pem

any ideas why?

I've looked at this,
https://github.com/nanomq/nanomq/discussions/1624

and I think it's not a server problem since I can connect using mqttx</div>

**Comment by JaylinYu** [comment]
you are probably using a version that has no TLS support

**Comment by KarlG-03** [comment]
Thanks! It works when I used `emqx/nanomq:latest-slim` instead of `emqx/nanomq:latest` as per the readme file.
I found the docs here https://github.com/nanomq/nanomq/blob/master/docs/en_US/installation/docker.md
