### ISSUE TITLE
0.22.8 Memory Leak

### ISSUE THREAD

**Issue by lizziemac** [nanomq/nanomq#1914]
**Describe the bug**
I updated my devices to use version 0.22.8, and I'm seeing a big memory leak occasionally. I had not seen a leak like this when on 0.21.5 (my previous version). I'm not entirely sure what's causing it, as I have info level logs, and nothing was printed at the start of the leaks, other than some system logs indicating network instability. Below is an image of _just_ the nanomq binary's memory over time, on two devices.

![image](https://github.com/user-attachments/assets/3e3cc3d6-69e7-45f6-9894-3e0d83f7c80f)

**Expected behavior**
The memory should stay consistent.

**Actual Behavior**
The memory climbs until the device can no longer allocate memory.

**To Reproduce**
I think that this may be reproducible by making the network unstable, while using QOS 2. For example, putting foil over a raspberry pi. I will try to reproduce here as well (these affected devices were remote/cannot be tested).

**Environment Details**
 - NanoMQ version:`0.22.8`
 - Operating system and version: Linux aarch64 - custom with linux kernel of 5.4.215
 - Compiler and language used: Yocto Dunfell, OECMAKE
 - testing scenario: Letting the device run nanomq over a long time.

**Client SDK**
Paho MQTT CPP

**Additional context**
Configuration
```yaml
# NanoMQ Configuration 0.18.0

# #============================================================
# # NanoMQ Broker
# #============================================================

mqtt {
    property_size = 32
    max_packet_size = 10KB
    max_mqueue_len = 2048
    retry_interval = 10s
    keepalive_multiplier = 1.25
    
    # Three of below, unsupported now
    max_inflight_window = 2048
    max_awaiting_rel = 10s
    await_rel_timeout = 10s
}

listeners.tcp {
    enable = false
}

listeners.ssl {
    enable = true
    bind = "0.0.0.0:8883"
    keyfile = "<path>"
    certfile = "<path>"
    cacertfile = "<path>"
    verify_peer = true
    fail_if_no_peer_cert = true
}

listeners.ws {
    enable = false
}

http_server {
    enable = false
}

log {
    to = [file, console]
    level = warn
    dir = "/tmp"
    file = "nanomq.log"
    rotation {
        size = 10MB
        count = 5
    }
}

auth {
    allow_anonymous = true # We don't use a username and password
    no_match = deny
    deny_action = disconnect
    
    cache = {
        max_size = 32
        ttl = 1m
    }
    
    acl = {include "/etc/nanomq_acl.conf"}
}
```

**Comment by JaylinYu** [comment]
There are 2 potential memleak issues were fixed last month, and they are not in 0.22.8. https://github.com/nanomq/nanomq/commit/377c035eaad539f0a3bfe1960ca34650fd6c86d7 & https://github.com/nanomq/nanomq/commit/377c035eaad539f0a3bfe1960ca34650fd6c86d7. 
But you are not using any bridging feature, so I doubt this is not your case.

 Are you using the retain msg or session-keeping feature of MQTT? If you send QoS msg to a cached session, the memory gonna increase for sure.

**Comment by JaylinYu** [comment]
After trying different kinds of cases. I still cannot reproduce your issue here.

No retain msg, clients are using clean start. It seems like the only possible change related to your case is "session expiry." 
I see you didnt enable the session-keeping feature but set "session expiry interval" with a max integar value, not sure what you up to here. Perhaps you can try to disable it.

BTW,  0.22.8 is also go through endurance test by other clients, no similar issue happened. I suspect the root cause of your problem, would be appreciated you can provide more details by setting log level to `info` or verify if the problem still exist in 0.22.6 & 0.21.10

**Comment by JaylinYu** [comment]
I recommend u update to 0.22.10. Perhaps you were hitting the same issue of 0.22.8, which was wrongly released on a not aligned commit.
