### ISSUE TITLE
NanoMQ panic caused by unaddressable memory in TCP sendmsg call

### ISSUE THREAD

**Issue by zzh-newlearner** [nanomq/nanomq#1924]
**Describe the bug**
A crash occurs in NanoMQ version 0.21.9 when attempting to send data over a TCP connection. The bug is triggered by an unaddressable memory access during a sendmsg system call. The error is identified by Valgrind in threads 7 and 11, where parameters in the sendmsg call point to unaddressable byte(s). This leads to a panic with an EFAULT error in the system, indicating a bug in the program.

**Expected behavior**
The TCP data should be sent successfully without any crashes or memory errors, and the program should continue running normally.

**Actual Behavior**
A crash occurs due to memory access violations during the TCP data sending process, leading to the program's unexpected termination.

**To Reproduce**
I have provided the message packet and the code that triggers the crash. Simply run `python nanomq_crash.py`, and the issue can be reproduced.
[nanomq_crash.zip](https://github.com/user-attachments/files/17490687/nanomq_crash.zip)

**Environment Details**
 - NanoMQ version v0.21.9
 - Operating system and version CentOS Linux 7 (Core)
 - Compiler and language used gcc (GCC) 8.3.1 20190311
 - testing scenario fuzz

**Additional context**
Details
==16408== Thread 7 nng:task:
==16408== Syscall param sendmsg(msg.msg_iov[3]) points to unaddressable byte(s)
==16408==    at 0x4E54C17: __libc_sendmsg (sendmsg.c:28)
==16408==    by 0x4E54C17: sendmsg (sendmsg.c:25)
==16408==    by 0x568C92: tcp_dowrite (posix_tcpconn.c:69)
==16408==    by 0x569B64: tcp_send (posix_tcpconn.c:293)
==16408==    by 0x50A9C3: nng_stream_send (stream.c:269)
==16408==    by 0x539FD9: nmq_pipe_send_start_v4 (broker_tcp.c:1148)
==16408==    by 0x53B681: tcptran_pipe_send_start (broker_tcp.c:1486)
==16408==    by 0x53B911: tcptran_pipe_send (broker_tcp.c:1515)
==16408==    by 0x469D0A: nni_pipe_send (pipe.c:138)
==16408==    by 0x48CBE5: nano_ctx_send (nmq_mqtt.c:441)
==16408==    by 0x4701F1: nni_ctx_send (socket.c:1438)
==16408==    by 0x455314: nng_ctx_send (nng.c:419)
==16408==    by 0x44D184: server_cb (broker.c:408)
==16408==  Address 0x5085e878 is not stack'd, malloc'd or (recently) free'd
==16408== 
==16408== Thread 11 nng:task:
==16408== Syscall param sendmsg(msg.msg_iov[0]) points to unaddressable byte(s)
==16408==    at 0x4E54C17: __libc_sendmsg (sendmsg.c:28)
==16408==    by 0x4E54C17: sendmsg (sendmsg.c:25)
==16408==    by 0x568C92: tcp_dowrite (posix_tcpconn.c:69)
==16408==    by 0x569B64: tcp_send (posix_tcpconn.c:293)
==16408==    by 0x50A9C3: nng_stream_send (stream.c:269)
==16408==    by 0x5375ED: nmq_tcptran_pipe_send_cb (broker_tcp.c:564)
==16408==    by 0x473F73: nni_taskq_thread (taskq.c:50)
==16408==    by 0x4752CA: nni_thr_wrap (thread.c:94)
==16408==    by 0x47AC66: nni_plat_thr_main (posix_thread.c:266)
==16408==    by 0x4E4ABDF: start_thread (pthread_create.c:486)
==16408==    by 0x55753BE: clone (clone.S:95)
==16408==  Address 0x5085e878 is not stack'd, malloc'd or (recently) free'd
==16408== 
panic: System EFAULT encountered!
This message is indicative of a BUG.
Report this at https://github.com/emqx/nanomq
nanomq(nni_panic+0x140) [0x469536]
nanomq(nni_plat_errno+0x66) [0x478e47]
nanomq() [0x568d70]
nanomq() [0x569b65]
nanomq(nng_stream_send+0x3a) [0x50a9c4]
nanomq() [0x5375ee]
nanomq() [0x473f74]
nanomq() [0x4752cb]
nanomq() [0x47ac67]
/lib64/libpthread.so.0(+0x7be0) [0x4e4abe0]
/lib64/libc.so.6(clone+0x3f) [0x55753bf]
2024-10-23 05:46:04 [16424] ERROR /targets/nanomq-0.21.9/nanomq/apps/broker.c:104 sig_handler: signal signumber: 6 received!

**Comment by JaylinYu** [comment]
Thanks for reporting security issue! Will fix it soon
