### ISSUE TITLE
Excessive Memory Usage Observed

### ISSUE THREAD

**Issue by shovel4hamburger** [nanomq/nanomq#1926]
**Describe the bug**
Upon sending a CONNECT packet to NanoMQ, the virtual memory size (VIRT) usage is observed to double. When NanoMQ is restarted, sending a large CONNACK packet (e.g., 100MB payload) to the broker results in the virtual memory size quadrupling. This significant memory usage appears excessive.

**Expected behavior**
The broker should handle CONNECT packets with a minimal increase in memory usage. Additionally, when receiving invalid or oversized packets, NanoMQ should handle these packets gracefully without causing a substantial increase in memory usage.

**Actual Behavior**
 1. Sending a CONNECT packet results in a doubled virtual memory usage (VIRT).
 2. Sending an oversized (100MB)  CONNACK packet after restarting NanoMQ results in memory usage quadrupling.

**To Reproduce**
 1. Start NanoMQ:
`nanomq start`
 2. Observe initial memory usage (VIRT).
 3. Send a standard MQTT CONNECT packet `b'\x10\x19\x00\x04\x4d\x51\x54\x54\x05\x02\x00\x3c\x03\x21\x00\x14\x00\x09\x63\x6c\x69\x65\x6e\x74\x5f\x69\x64'` to NanoMQ and observe the virtual memory increase using `top -p pid`
 4. Restart NanoMQ:
 `nanomq start`
 5. Send a large invalid CONNACK packet (approximately 100MB) `b"\x20\x80\x80\x80t" + b"\03"*100000000 `to NanoMQ.
 6. Observe the virtual memory usage increase using `top -p pid`
 
**Environment Details**

- NanoMQ version: 0.22.8
- Operating system and version: Ubuntu 20.04 LTS
- Compiler and language used: C/C++
- Testing scenario: Observe memory usage (VIRT) when sending MQTT packets.

**Additional context**
In addition, I found that if the CONNACK message is sent directly, the VIRT will suddenly become four times the original value. However, if CONNECT is sent first and then CONNACK, the VIRT will not have an obvious change of doubling based on CONNECT.
Below is the screenshots of VIRT：
VIRT when the broker starts：
![initial](https://github.com/user-attachments/assets/3526a496-5cce-497e-8b82-f252e1289115)
VIRT after seneding the CONNECT packet:
![image](https://github.com/user-attachments/assets/ab01455a-ca17-4149-bcd5-53436d0740c9)
VIRT after restarting the broker and sending the CONNACK packet:
![image](https://github.com/user-attachments/assets/8b06e265-fbf3-4c69-9eeb-b715abb06da1)

**Comment by JaylinYu** [comment]
This is not even an issue; please Learn the MMP of Linux to understand VIRT.
