### ISSUE TITLE
Connection Not Rejected When Providing Only Username

### ISSUE THREAD

**Issue by Sea-Intestine-Rice** [nanomq/nanomq#1928]
**Describe the bug**
When I set allow_anonymous = False in the NanoMQ configuration and configured password = {include "/etc/nanomq_pwd.conf"}, I expected the connection to be rejected if the client only provides a username without a password. However, the connection is not rejected.

**Expected behavior**
I expected that when the client provides only a username without a password, NanoMQ should reject the connection request.

**Actual Behavior**
The client successfully connects.

**To Reproduce**
 1. In the NanoMQ configuration file /etc/nanomq.conf, add the following content:
  ```
   auth {
            allow_anonymous = False
            password = {include "/etc/nanomq_pwd.conf"}
      }
  ```
  2. In /etc/nanomq_pwd.conf, add the following content:
      ```
        "admin": "public",
          "client": "public"
      ```
   3. Start NanoMQ with:
      `nanomq start  --conf /etc/nanomq.conf`
   4. Attempt to connect without providing a password with hexstream:
      ` 101c00044d5154540582000a032100140005756e616d65000561646d696e`
   
**Environment Details**

- NanoMQ version 0.22.8
- Operating system and version Ubuntu 22.04 LTS
- Compiler and language used C/C++
- Testing scenario: Connecting with an MQTT client where only the username is provided.

**Additional context**
Connections without a password should be rejected, but they are currently allowed. Please help confirm if this behavior is expected or if there is a configuration issue. 
[no_password.zip](https://github.com/user-attachments/files/17533114/no_password.zip)

**Comment by JaylinYu** [comment]
Your config file is wrong, if you want broker to kick out client with invalid auth info, plz refer to
```


  auth {
      allow_anonymous = false
      no_match = deny
      deny_action = disconnect

      cache = {
          max_size = 32
          ttl = 1m
      }

      password = {include "/etc/nanomq_pwd.conf"}
  }
```

**Comment by Sea-Intestine-Rice** [comment]
Thank you for the guidance.
