### ISSUE TITLE
Will Message Not Published Issue

### ISSUE THREAD

**Issue by Sea-Intestine-Rice** [nanomq/nanomq#1929]
**Describe the bug**
I configured NanoMQ to use a password file for authentication and disabled anonymous access. When a client with username=admin and password=password sends a CONNECT packet with a Will Message set, the expected Will Message is not published.

**Expected behavior**
The Will Message should be published to the specified topic (will/test) when the client disconnects unexpectedly.

**Actual Behavior**
After the client sends a CONNECT packet with the Will Flag enabled and subsequently pings, the Will Message is not published as expected on the specified topic.

**To Reproduce**
  1. Configure NanoMQ with the following configuration:
  ```
 mqtt {
        property_size = 32
        max_packet_size = 260MB
        max_mqueue_len = 2048
        retry_interval = 10s
        keepalive_multiplier = 1.25
    }
    
    listeners.tcp {
        bind = "0.0.0.0:1883"
    }
    
    listeners.ws {
        bind = "0.0.0.0:8083/mqtt"
    }
    
    http_server {
        port = 8081
        limit_conn = 2
        username = admin
        password = password
        auth_type = basic
    }
    
   
    auth {
        allow_anonymous = False
        no_match = allow
        deny_action = ignore
        
        cache = {
            max_size = 32
            ttl = 1m
        }
        
        password = {include "nanomq_pwd.conf"}
    }
```
  2. nanomq_pwd.conf file content:
```
  "admin": "password"
  "client": "public"
```
 3. Send a CONNECT packet with the following parameters:

   ```
    Username: admin
    Password: password
    Will Topic: will/test
    Will Message: will msg
    Will Flag: set
hexstream:104800044d51545405c6000a032100140011636f6e6e6563742d77696c6c2d7465737400000977696c6c2f74657374000877696c6c206d7367000561646d696e000870617373776f7264

```
  4.  The client then ping the broker.

**Environment Details**

- NanoMQ version: 0.22.8
- Operating system and version: Ubuntu 20.04 LTS
- Compiler and language used: C/C++
- Testing scenario: Client sends a Will Message  and expects the Will Message to be published by the broker.     

**Additional context**
[will.zip](https://github.com/user-attachments/files/17533516/will.zip)

**Comment by JaylinYu** [comment]
Just tested it with your case, will msg works.
Please check if the client send a  Disconnect packet to close the connection gracefully, in this case the will msg will be dropped

**Comment by Sea-Intestine-Rice** [comment]
Thank you for your response! 
To clarify, after sending a PING, the client disconnects by directly closing the socket without sending a DISCONNECT packet. According to the MQTT protocol, in cases of an ungraceful disconnection , the broker should retain and publish the Will Message as configured in the CONNECT packet. This setup matches the expected behavior for an unexpected disconnection, where the broker should detect the broken connection and publish the Will Message.

**Comment by JaylinYu** [comment]
You didnt understand my answer.... Will msg is absolutely working.
The hex example you posted is not even a valid CONNECT packet, therefore no connection is ever established, how come a will msg will be published?
