### ISSUE TITLE
Offline messages are not received upon reconnecting non-clean session client

### ISSUE THREAD

**Issue by jarhodes314** [nanomq/nanomq#1934]
**Describe the bug**
I am attempting to use nanomq with `clean_session false` to ensure messages are not lost when my client is offline. However, the client does not receive the messages sent when it was offline.

**Expected behavior**
If I:
1. Connect a client with id `test-client` with `clean_session=False`
2. Subscribe to the topic `test-subscription`
3. Disconnect the client cleanly
4. Publish a message from a different client to `test-subscription`
5. Reconnect the original client with the same id and `clean_session` still false, and re-subscribe to `test-subscription`
 
The message sent while the client was offline should be received

**Actual Behavior**
No message was received upon completion of step 5.

**To Reproduce**
Here is the Python script I have written to test the behaviour of a clean session connection. It generates a random client ID for each execution of the script, to avoid any persistence related weirdness (although I don't believe there's any reason this should affect the behaviour).

The script has a single dependency, you can install it by running:

```bash
pip install paho-mqtt
```

```python
import paho.mqtt.client as mqtt
import string
import random
import paho.mqtt.publish as publish
from time import time

def on_subscribe(client, userdata, mid, reason_code_list, properties):
    # Since we subscribed only for a single channel, reason_code_list contains
    # a single entry
    if reason_code_list[0].is_failure:
        print(f"Broker rejected you subscription: {reason_code_list[0]}")
    else:
        userdata.subscribed = True

def on_disconnect(client, userdata):
    pass

def on_message(client, userdata, message):
    userdata.messages.append(message.payload.decode('utf-8'))

def on_connect(client, userdata, flags, reason_code, properties):
    print("Receive client connected to broker")
    if reason_code.is_failure:
        print(f"Failed to connect: {reason_code}. loop_forever() will retry connection")
    else:
        # we should always subscribe from on_connect callback to be sure
        # our subscribed is persisted across reconnections.
        client.subscribe("test-subscription", qos=1)


def gen_id(n):
    return ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(n))


class MqttState:
    def __init__(self):
        self.messages = []
        self.subscribed = False

# Subscribe with clean_session false. If we change this to true (and restart nanomq), everything works
mqttc = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2, client_id=f"test-client-{gen_id(7)}", clean_session=False)
mqttc.on_connect = on_connect
mqttc.on_message = on_message
mqttc.on_subscribe = on_subscribe

TIMEOUT = 5
HOST = "localhost"

mqttc.connect(HOST)

mqttc.user_data_set(MqttState())


while True:
    start = time()
    rc = mqttc.loop(timeout=TIMEOUT)
    if mqttc.user_data_get().subscribed:
        mqttc.disconnect()
        break
    if time() - start > TIMEOUT:
        mqttc.disconnect()
        raise Exception(f"Timed out after {TIMEOUT} seconds waiting for SUBACK")

# Publish a message while the client is not connected
# If clean_session false is working, we will receive this message upon reconnection
publish.single("test-subscription", "offline message", hostname="localhost", qos=1)
print("Published message while receive client disconnected")

mqttc.user_data_set(MqttState())
mqttc.connect(HOST)
while True:
    start = time()
    rc = mqttc.loop(timeout=TIMEOUT)
    if len(mqttc.user_data_get().messages) > 0:
        print("PASSED - Received message sent while offline")
        mqttc.disconnect()
        break
    if time() - start > TIMEOUT:
        mqttc.disconnect()
        raise Exception(f"Timed out after {TIMEOUT} seconds waiting for message after reconnecting")
```

**Environment Details**
 - Docker image: `emqx/nanomq:0.22.8`
 - Ubuntu 22.04

**Client SDK**
Python `paho-mqtt 2.1.0`

**Additional context**
I have verified the script works as intended against both mosquitto and HiveMQ.

**Comment by JaylinYu** [comment]
There is a config param called `retry_interval` which is always being neglected. refer to https://nanomq.io/docs/en/latest/config-description/mqtt.html#example-configuration. By default is 10s, which means you will need to wait 10s after reconnect.
You would need to set it to 1s, if a swift msg retry is expected. But only QoS 1/2 msg with same clientID will be cached and resended.

**Comment by JaylinYu** [comment]
There is a config param called `retry_interval` that is always neglected. Refer to https://nanomq.io/docs/en/latest/config-description/mqtt.html#example-configuration. The default is 10s, which means you will need to wait 10s after reconnecting.
If a swift message retry is expected, you would need to set it to 1s. However, only QoS 1/2 messages with the same clientID will be cached and presented.

**Comment by reubenmiller** [comment]
> There is a config param called `retry_interval` which is always being neglected. refer to https://nanomq.io/docs/en/latest/config-description/mqtt.html#example-configuration. By default is 10s, which means you will need to wait 10s after reconnect. You would need to set it to 1s, if a swift msg retry is expected. But only QoS 1/2 msg with same clientID will be cached and resended.

Upon reconnection of a client using the same Client ID and cleansession=false, are QoS 1/2 messages sent to the client after the `retry_interval` one by one, waiting for the `retry_interval` between re-sending each message?

**Comment by JaylinYu** [comment]
> > There is a config param called `retry_interval` which is always being neglected. refer to https://nanomq.io/docs/en/latest/config-description/mqtt.html#example-configuration. By default is 10s, which means you will need to wait 10s after reconnect. You would need to set it to 1s, if a swift msg retry is expected. But only QoS 1/2 msg with same clientID will be cached and resended.
> 
> 
> 
> Upon reconnection of a client using the same Client ID and cleansession=false, are QoS 1/2 messages sent to the client after the `retry_interval` one by one, waiting for the `retry_interval` between re-sending each message?

Correct, and I know you would day it is too slow, hence there is a batch resend PR not merged yet.

**Comment by jarhodes314** [comment]
I also don't appear to receive retain messages that have received on previous connections (i.e. if I send a message with the retain flag, receive it, disconnect then reconnect, I don't get resent the retain message). I believe that any retain messages should be resent every time I subscribe to the topic in question, regardless of whether the session is clean or not:

> [MQTT-3.8.4-3]
> If a Server receives a SUBSCRIBE Packet containing a Topic Filter that is identical to an existing Subscription’s Topic Filter then it MUST completely replace that existing Subscription with a new Subscription. The Topic Filter in the new Subscription will be identical to that in the previous Subscription, although its maximum QoS value could be different. Any existing retained messages matching the Topic Filter MUST be re-sent, but the flow of publications MUST NOT be interrupted.

**Comment by JaylinYu** [comment]
> I also don't appear to receive retain messages that have received on previous connections (i.e. if I send a message with the retain flag, receive it, disconnect then reconnect, I don't get resent the retain message). I believe that any retain messages should be resent every time I subscribe to the topic in question, regardless of whether the session is clean or not:
> 
> > [MQTT-3.8.4-3]
> > If a Server receives a SUBSCRIBE Packet containing a Topic Filter that is identical to an existing Subscription’s Topic Filter then it MUST completely replace that existing Subscription with a new Subscription. The Topic Filter in the new Subscription will be identical to that in the previous Subscription, although its maximum QoS value could be different. Any existing retained messages matching the Topic Filter MUST be re-sent, but the flow of publications MUST NOT be interrupted.

Just Test it again on my laptop, it works fine. Will be published each time a client sub to the retain topic.
And your understanding is correct, retain msg has nothing to do with clean start flag.

**Comment by jarhodes314** [comment]
> > I also don't appear to receive retain messages that have received on previous connections (i.e. if I send a message with the retain flag, receive it, disconnect then reconnect, I don't get resent the retain message). I believe that any retain messages should be resent every time I subscribe to the topic in question, regardless of whether the session is clean or not:
> > 
> > > [MQTT-3.8.4-3]
> > > If a Server receives a SUBSCRIBE Packet containing a Topic Filter that is identical to an existing Subscription’s Topic Filter then it MUST completely replace that existing Subscription with a new Subscription. The Topic Filter in the new Subscription will be identical to that in the previous Subscription, although its maximum QoS value could be different. Any existing retained messages matching the Topic Filter MUST be re-sent, but the flow of publications MUST NOT be interrupted.
> 
> Just Test it with mqttx/mosquitto again on my laptop, it works fine. The retain msg Will be published each time a client sub to the retain topic. Only one retain msg will be stored for one topic.
> And your understanding is correct, retaining msg has nothing to do with clean start flag. 

So I see nanomq is sending the retain messages following the suback. This means that when I call subscribe twice 
 within a single session, I get sent the retain messages with both subscriptions as expected. However if I send a retain message, connect the non clean session client, then reconnect the client, I don't appear to receive a suback nor the retain message I previously received.

**Comment by JaylinYu** [comment]
As long as the client subscribe to that topic with a persistent retaining msg, nano Will Publish the retain msg. Works fine here. Not sure what is wrong in your place. 
I can follow up if you have a stable reproduce method

**Comment by jarhodes314** [comment]
Here's the script I was using for testing. It sends a retain message, connects and checks we've received it, then reconnects and doesn't receive the message when running against nanomq locally for me.

```python
import paho.mqtt.client as mqtt
import string
import random
import paho.mqtt.publish as publish
from time import time

def on_subscribe(client, userdata, mid, reason_code_list, properties):
    # Since we subscribed only for a single channel, reason_code_list contains
    # a single entry
    if reason_code_list[0].is_failure:
        print(f"Broker rejected you subscription: {reason_code_list[0]}")
    else:
        print("Sucessfully subscribed")
        userdata.subscribed = True

def on_message(client, userdata, message):
    userdata.messages.append(message.payload.decode('utf-8'))

def on_connect(client, userdata, flags, reason_code, properties):
    print("Receive client connected to broker")
    if reason_code.is_failure:
        print(f"Failed to connect: {reason_code}. loop_forever() will retry connection")
    else:
        # we should always subscribe from on_connect callback to be sure
        # our subscribed is persisted across reconnections.
        client.subscribe("test-subscription", qos=1)
        print("Attempting to subscribe to 'test-subscription'")


def gen_id(n):
    return ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(n))


class MqttState:
    def __init__(self):
        self.messages = []
        self.subscribed = False

print(f"test-client-{gen_id(7)}")

mqttc = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2, client_id=f"test-client-{gen_id(7)}", clean_session=False, manual_ack=False)
mqttc.on_connect = on_connect
mqttc.on_message = on_message
mqttc.on_subscribe = on_subscribe

TIMEOUT = 5
HOST = "localhost"

mqttc.connect(HOST)

mqttc.user_data_set(MqttState())

publish.single("test-subscription", "retained message", hostname=HOST, qos=1, retain=True)
print("Published retain message")

start = time()
while True:
    looped = time()
    rc = mqttc.loop(timeout=TIMEOUT / 2)
    if time() - looped > TIMEOUT / 2 and len(mqttc.user_data_get().messages) > 0:
        mqttc.disconnect()
        break
    if time() - start > TIMEOUT:
        mqttc.disconnect()
        raise Exception(f"Timed out after {TIMEOUT} seconds waiting for SUBACK")

mqttc.user_data_set(MqttState())
mqttc.connect(HOST)
while True:
    start = time()
    rc = mqttc.loop(timeout=TIMEOUT)
    if len(mqttc.user_data_get().messages) > 0:
        print("PASSED - Received message sent while offline")
        print(mqttc.user_data_get().messages.pop())
        mqttc.disconnect()
        break
    if time() - start > TIMEOUT:
        mqttc.disconnect()
        raise Exception(f"Timed out after {TIMEOUT} seconds waiting for message after reconnecting")
```

**Comment by JaylinYu** [comment]
output is :

```
test-client-Z7TMG96
Published retain message
Receive client connected to broker
Attempting to subscribe to 'test-subscription'
Sucessfully subscribed
Receive client connected to broker
Attempting to subscribe to 'test-subscription'
PASSED - Received message sent while offline
retained message

```

**Comment by jarhodes314** [comment]
Okay, it's working from the docker 0.22.8, but not the amd64 deb package 0.22.8 downloaded from the releases page for me.

I have tried with both no config file and the following and achieved the same result with the locally installed version

```
mqtt.retry_interval = 3s
```

**Comment by JaylinYu** [comment]
Pretty weird....
They Shall be the same...

**Comment by jarhodes314** [comment]
I've done a test with the amd64 deb packages. Any of the 0.22.8 deb packages exhibit the failure, the 0.22.7 equivalents don't.

If I use the `emqx/nanomq:0.22.7` docker image, that also doesn't receive the message.

**Comment by reubenmiller** [comment]
Though one thing that I've observed with the packaging is that the docker image tags don't full the same as the linux packaging, for example:

**Docker**

* `emqx/nanomq:latest` (size ~3MB)
* `emqx/nanomq:latest-slim` (size ~32MB)
* `emqx/nanomq:latest-full` (size ~70MB)

Also, the `latest` tag is larger than the `latest-slim` which is slightly unexpected, but I guess this could be debatable.

**Linux Packaging**

* `nanomq`
* `nanomq` (sqlite)
* `nanomq` (msquic)
* `nanomq` (full)

So maybe this misalignment when comparing the different packages 
 is also adding to the confusion.

**Comment by JaylinYu** [comment]
Indeed, I found out the 0.22.8 tag was on the wrong commit. Just don't know what went wrong, some important PRs is missing, perhaps some DevOps mistake when republishing 0.22.8 release.

I have retag 0.22.8 again, sorry for the troubles.
