### ISSUE TITLE
有没有办法实现MQTT用户名密码动态添加，一机一密

### ISSUE THREAD

**Issue by DenisZheng** [nanomq/nanomq#1941]
**Is your feature request related to a problem? Please describe.**
小型局域网系统想实现设备一机一密功能，Emqx比较重

**Describe the solution you'd like**
设备通过自研系统注册，系统后端调用NanoMQ写入设备独有的MQTT用户名密码，并下发给设备保存，设备后续使用该MQTT用户名密码进行通讯

**Describe alternatives you've considered**

**Additional context**

**Comment by JaylinYu** [comment]
你可以使用HTTP AUTH 插件
