### ISSUE TITLE
core dumped at nanomq startup

### ISSUE THREAD

**Issue by zzflytang** [nanomq/nanomq#1943]
If the nanomq.pid file in the tmp directory is not deleted, perform a core dump on the next startup.

I looked at the source code and it seems that the “pid_path” were released.

![PixPin_2024-11-18_16-20-30](https://github.com/user-attachments/assets/58098f0b-1228-4a1c-a8a6-87bb5706151b)

**Comment by JaylinYu** [comment]
Mhhhh... This is a pid Check to prevent user wrongly spawn multiple nanomq with mistakes. And it Shall not core dump, the actual behavior is exit with a warning. Perhaps looks like a core dump in your system. Or Plz provide your core file, we can keep on investing.

If This cause trouble for u, you can simply remove the Check as well

**Comment by zzflytang** [comment]
I moved this code "nnd_strfree (pid_path)" after "nnd_file_delete (pid_path)" and solved the problem. You can fix this issue in the next version.

![PixPin_2024-11-18_17-24-55](https://github.com/user-attachments/assets/0de58a16-4360-4339-8b56-557dcad7adbe)

**Comment by JaylinYu** [comment]
Thanks for your issue debugging!
