### ISSUE TITLE
Nanomq script is not good since nng should be clone too in order to avoid compilation error

### ISSUE THREAD

**Issue by antonymarion** [nanomq/nanomq#1947]
File: [/docs/en_US/gateway/dds.md](https://nanomq.io/docs/en/latest/gateway/dds.html)

cf https://github.com/nanomq/nanomq/issues/1518

**Comment by wanghaEMQ** [comment]
Cool. Documents have been updated. https://github.com/nanomq/nanomq/pull/1951
