### ISSUE TITLE
HTTP SERVER

### ISSUE THREAD

**Issue by amcharhal** [nanomq/nanomq#1948]
Hello,

I have a question about the HTTP server provided with NanoMQ.

As far as I know, this HTTP server can be used to update bridges and configuration. This means we need to send the username and password over HTTP requests. I’m wondering if there are any plans to provide an HTTPS server instead of HTTP in order to secure these requests, for example, by using TLS. It seems critical to address this issue.

**Comment by JaylinYu** [comment]
You can secure HTTP VIA JWT and basic authentication

**Comment by amcharhal** [comment]
thank you for you answer,  @JaylinYu 
 and  can we bind http server access only to localhost

**Comment by JaylinYu** [comment]
You can try set HTTP Sever's url to 127.0.0.1

**Comment by amcharhal** [comment]
The documentation config does not include the URL of the HTTP server in its parameters. However, upon reviewing the file nanomq_cli/include/rest_api.h, I noticed that the HTTP server URL is hard-coded #define REST_HOST "http://0.0.0.0:%u"

// config http server 
http_server = {
  port = 8081               # HTTP server port
  limit_conn = 32           # Maximum number of outstanding requests NanoMQ can handle
  username = "admin"        # Username
  password = "public"       # Password
  auth_type = "jwt"         # Authentication type, "basic" or "jwt"
  jwt = {
    public.keyfile = "/etc/certs/jwt/jwtRS256.key.pub"   # Path to the JWT public key file, used if auth_type is "jwt"
  }
}
