### ISSUE TITLE
startup/stop bug of pid file check logic

### ISSUE THREAD

**Issue by zzflytang** [nanomq/nanomq#1961]
some bug in pid file check logic
1. nanomq execute twice, The pid file was deleted by mistake and write the wrong content
    1) The first execute, pid = 278718 is correct
    2) The second execute, The pid file was deleted by mistake and write the wrong content(278843)
    3) Actually, the pid is still 278718
![1](https://github.com/user-attachments/assets/869b856d-e89c-4115-b8c7-3c16dd95095a)

2. The "nanomq stop" operation will delete the .pid file first, Causing running NanoMQ instances to be unable to be discovered
    
![2](https://github.com/user-attachments/assets/879dcf4a-3d9a-437c-ab8b-eca81ae5d68c)

 - NanoMQ 0.23.1
 - rocky 9.5
 - gcc

**Comment by zzflytang** [comment]
suggestion
![3](https://github.com/user-attachments/assets/e8404614-5f39-4183-89d9-1de7e5cca127)

[0002-fix.patch](https://github.com/user-attachments/files/18175720/0002-fix.patch)

**Comment by JaylinYu** [comment]
Thanks for your suggestion. How about you make it as PR, credit goes to u

**Comment by zzflytang** [comment]
I tried submitting a PR, Pls check.


         原始邮件
         
       
发件人：                  Jaylin         ***@***.***                 
发件时间：         2024年12月20日 09:07 
收件人：                  nanomq/nanomq         ***@***.***                 
抄送：                  zzflytang         ***@***.***         ,                Author         ***@***.***                 
主题：         Re: [nanomq/nanomq] startup/stop bug of pid file check logic (Issue#1961) 




Thanks for your suggestion. How about you make it as PR, credit goes to u

**Comment by JaylinYu** [comment]
merged
