### ISSUE TITLE
nanolib & nng Build Errors on Raspberry pi 3b+

### ISSUE THREAD

**Issue by mahmoodfathy** [nanomq/nanomq#256]
When trying to build nng from source using the following command ` sudo  make ` it has the following error

```
Scanning dependencies of target nng
[  0%] Building C object CMakeFiles/nng.dir/src/nng.c.o
In file included from /home/pi/nanomq/nng/src/core/nng_impl.h:37,
                 from /home/pi/nanomq/nng/src/nng.c:12:
/home/pi/nanomq/nng/src/core/message.h:14:10: fatal error: packet.h: No such file or directory
 #include <packet.h>
          ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/nng.dir/build.make:63: CMakeFiles/nng.dir/src/nng.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:902: CMakeFiles/nng.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

```

and also when trying to build nanolin with the same command it errors the following:
```
[ 36%] Building C object CMakeFiles/nanolib.dir/conf.c.o
/home/pi/nanomq/nanolib/conf.c:14:10: fatal error: nanomq.h: No such file or directory
 #include "nanomq.h"
          ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/nanolib.dir/build.make:102: CMakeFiles/nanolib.dir/conf.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:108: CMakeFiles/nanolib.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

i can't seem to build those dependencies from source

**Comment by mahmoodfathy** [comment]
`sudo cmake -G Ninja` hangs and never resolve to anything from the stdout

**Comment by JaylinYu** [comment]
This is a known issue. For now if you wanna build nng independently for MQTT SDK, please try nng-mqtt branch. We are busy developing NanoMQ's bridging feature in Master branch which cause some dependency issue like this one. We will fix it in the next relaease.

**Comment by JaylinYu** [comment]
BTW if you are trying to buiuld nanomq broker, just move to root directory of NanoMQ project, then:
mkdir build && cd build
cmake -G Ninja ..
ninja

**Comment by mahmoodfathy** [comment]
Nanomq broker was built successfully With no issues when following this:
mkdir build && cd build
cmake -G Ninja ..
The problem was with nanolib and nng only

**Comment by JaylinYu** [comment]
I am closing this, because this does not affect anything,
