### ISSUE TITLE
nanomq.conf & nanomq_auth_username.conf template support

### ISSUE THREAD

**Issue by ZodiacWind** [nanomq/nanomq#257]
I want to configure nanomq with configuration files, but I don't find configuration template from the repository. Could anyone provide a template please? Or where could I find them?

**Comment by JaylinYu** [comment]
here : https://github.com/nanomq/nanomq/blob/master/etc/nanomq.conf
nanomq broker start -conf $(your nanomq.conf)

**Comment by ZodiacWind** [comment]
Thank you very much. I got them.
Btw, I noticed that the documentation might be confusing that I keep searching in `./nanomq/etc' of my local coomputer.

**Comment by JaylinYu** [comment]
Readme updated
