### ISSUE TITLE
nanomq broker Segmentation fault.

### ISSUE THREAD

**Issue by lee-emqx** [nanomq/nanomq#273]
When I use mqtt client subscribe topic #, and I cancel it by hit Ctrl-c, nanomq broker will output Segmentation fault directly.

**Comment by wanghaEMQ** [comment]
Hi, I noticed this bug which was caused by system_topic. I fixed it at #274.

**Comment by wanghaEMQ** [comment]
If there are no problems, I will close this issue later.

**Comment by JaylinYu** [comment]
Temp fix for now.
