### ISSUE TITLE
ubuntu nanomq build erro

### ISSUE THREAD

**Issue by tlchun** [nanomq/nanomq#283]
OS: ubuntu
gcc:10.2.0
cmake:3.130 或者 3.19.1
In file included from /usr/include/features.h:367:0,
                 from /usr/include/assert.h:35,
                 from /home/tlc/nanomq/nanolib/include/cvector.h:5,
                 from /home/tlc/nanomq/nanolib/include/hash.h:4,
                 from /home/tlc/nanomq/nanolib/hash.cc:9:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:109:1: error: expected unqualified-id before ‘throw’
 __MATHCALL_VEC (log,, (_Mdouble_ __x));
 ^
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/tlc/nanomq/nanolib/hash.cc:11:
/usr/include/c++/5/cmath:353:11: error: ‘::log’ has not been declared
   using ::log;
           ^
In file included from /usr/include/c++/5/random:49:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/tlc/nanomq/nanolib/hash.cc:11:
/usr/include/c++/5/bits/random.h: In member function ‘void std::geometric_distribution<_IntType>::param_type::_M_initialize()’:
/usr/include/c++/5/bits/random.h:3876:36: error: call of overloaded ‘log(double)’ is ambiguous
  { _M_log_1_p = std::log(1.0 - _M_p); }
                                    ^
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/tlc/nanomq/nanolib/hash.cc:11:
/usr/include/c++/5/cmath:357:3: note: candidate: constexpr float std::log(float)
   log(float __x)
   ^
/usr/include/c++/5/cmath:361:3: note: candidate: constexpr long double std::log(long double)
   log(long double __x)
   ^
In file included from /usr/include/c++/5/random:51:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/tlc/nanomq/nanolib/hash.cc:11:
/usr/include/c++/5/bits/random.tcc: In member function ‘void std::poisson_distribution<_IntType>::param_type::_M_initialize()’:
/usr/include/c++/5/bits/random.tcc:1249:32: error: call of overloaded ‘log(double&)’ is ambiguous
    _M_lm_thr = std::log(_M_mean);
                                ^
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/tlc/nanomq/nanolib/hash.cc:11:
/usr/include/c++/5/cmath:357:3: note: candidate: constexpr float std::log(float)
   log(float __x)
   ^
/usr/include/c++/5/cmath:361:3: note: candidate: constexpr long double std::log(long double)
   log(long double __x)
   ^
In file included from /usr/include/c++/5/random:51:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/tlc/nanomq/nanolib/hash.cc:11:
/usr/include/c++/5/bits/random.tcc:1255:22: error: call of overloaded ‘log(double)’ is ambiguous
              / __pi_4));
                      ^
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/tlc/nanomq/nanolib/hash.cc:11:
/usr/include/c++/5/cmath:357:3: note: candidate: constexpr float std::log(float)
   log(float __x)
   ^
/usr/include/c++/5/cmath:361:3: note: candidate: constexpr long double std::log(long double)
   log(long double __x)
   ^
In file included from /usr/include/c++/5/random:51:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/tlc/nanomq/nanolib/hash.cc:11:
/usr/include/c++/5/bits/random.tcc: In member function ‘void std::binomial_distribution<_IntType>::param_type::_M_initialize()’:
/usr/include/c++/5/bits/random.tcc:1463:33: error: call of overloaded ‘log(double)’ is ambiguous
           / (81 * __pi_4 * __1p)));
                                 ^
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/tlc/nanomq/nanolib/hash.cc:11:
/usr/include/c++/5/cmath:357:3: note: candidate: constexpr float std::log(float)
   log(float __x)
   ^
/usr/include/c++/5/cmath:361:3: note: candidate: constexpr long double std::log(long double)
   log(long double __x)
   ^
In file included from /usr/include/c++/5/random:51:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/tlc/nanomq/nanolib/hash.cc:11:
/usr/include/c++/5/bits/random.tcc:1486:34: error: call of overloaded ‘log(double)’ is ambiguous
    _M_lp1p = std::log(__pa / __1p);
                                  ^
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/tlc/nanomq/nanolib/hash.cc:11:
/usr/include/c++/5/cmath:357:3: note: candidate: constexpr float std::log(float)
   log(float __x)
   ^
/usr/include/c++/5/cmath:361:3: note: candidate: constexpr long double std::log(long double)
   log(long double __x)
   ^
In file included from /usr/include/c++/5/random:51:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/tlc/nanomq/nanolib/hash.cc:11:
/usr/include/c++/5/bits/random.tcc:1488:46: error: call of overloaded ‘log(double)’ is ambiguous
    _M_q = -std::log(1 - (__p12 - __pa) / __1p);
                                              ^
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/tlc/nanomq/nanolib/hash.cc:11:
/usr/include/c++/5/cmath:357:3: note: candidate: constexpr float std::log(float)
   log(float __x)
   ^
/usr/include/c++/5/cmath:361:3: note: candidate: constexpr long double std::log(long double)
   log(long double __x)
   ^
In file included from /usr/include/c++/5/random:51:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/tlc/nanomq/nanolib/hash.cc:11:
/usr/include/c++/5/bits/random.tcc:1492:28: error: call of overloaded ‘log(double)’ is ambiguous
  _M_q = -std::log(1 - __p12);
                            ^
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/tlc/nanomq/nanolib/hash.cc:11:
/usr/include/c++/5/cmath:357:3: note: candidate: constexpr float std::log(float)
   log(float __x)
   ^
/usr/include/c++/5/cmath:361:3: note: candidate: constexpr long double std::log(long double)
   log(long double __x)
   ^
nanolib/CMakeFiles/nanolib.dir/build.make:62: recipe for target 'nanolib/CMakeFiles/nanolib.dir/hash.cc.o' failed
make[2]: *** [nanolib/CMakeFiles/nanolib.dir/hash.cc.o] Error 1
CMakeFiles/Makefile2:2684: recipe for target 'nanolib/CMakeFiles/nanolib.dir/all' failed
make[1]: *** [nanolib/CMakeFiles/nanolib.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JaylinYu** [comment]
> Hey, this error was caused by the STL (standard library in CPP). Our hashtable is under development. If you want to fix it now, upgrade your g++.

The hashtable module is going to be obsoleted.

**Comment by JaylinYu** [comment]
this is fixed by removing hash.cc
