### ISSUE TITLE
建议增加配置文件

### ISSUE THREAD

**Issue by skyformat99** [nanomq/nanomq#29]
与其编译的时候设置参数，不如使用配置文件来实现。
比如说，ini文件，或者普通的linux配置文件格式都行。

另外，
建议增加用户，密码访问方式；
增加topic过滤功能。

目前来看，似乎只是一个简单的消息中转站。

**Comment by JaylinYu** [comment]
Yes One of many TODOs

**Comment by JaylinYu** [comment]
配置文件已增加

**Comment by skyformat99** [comment]
666

**Comment by skyformat99** [comment]
越来越牛了，再提一点点建议
1）内置一些特殊的topic，可以接收上下线event，可以统计当前在线设备和数量
2）增加user /password ，类似 mosquito

**Comment by JaylinYu** [comment]
Thanks for your advice.
将作为开发计划实现。

**Comment by JaylinYu** [comment]
user /password 已增加

**Comment by skyformat99** [comment]
> user /password 已增加

666

**Comment by JaylinYu** [comment]
上下线主题也已经实现
$SYS/brokers/connected
$SYS/brokers/disconnected

**Comment by JaylinYu** [comment]
增加topic过滤功能  -->ACL?
