### ISSUE TITLE
sub qos is not available when topic includes wildcard '+' or '#'...

### ISSUE THREAD

**Issue by wanghaEMQ** [nanomq/nanomq#327]
refer to file pub_handler.c:66 line

```c
		while (tn) {
			if (0 == strcmp(tn->it->topic_filter.body,
			        pub_work->pub_packet->variable_header.publish.topic_name.body)) {
				sub_qos = tn->it->qos;
				break;
			}
			tn = tn->next;
		}

```

**Comment by wanghaEMQ** [comment]
@lee-emqx Is there are any functions that can be used to determine whether a topic complies with a topic with a wildcard.

for example. something like this....

```
true  = mqtt_topic_compare("test/a", "test/*");
false = mqtt_topic_compare("msg", "test/*");
```

**Comment by wanghaEMQ** [comment]
@alvin1221 Help!!!

**Comment by alvin1221** [comment]
You can refer to  [bridge.c](https://github.com/nanomq/nanomq/blob/master/nanomq/bridge.c): 152, function `topic_filter()`

**Comment by wanghaEMQ** [comment]
Thank u
