### ISSUE TITLE
Mqtt v5 client subscribe topic can not receive suback, but v311 can receive?

### ISSUE THREAD

**Issue by lee-emqx** [nanomq/nanomq#337]
@wanghaEMQ pls check.
`$ mosquitto_sub -t a/b/c  -d -V 5`

Client (null) sending CONNECT
Client nanomq-7c3fd1d5 received CONNACK (0)
Client nanomq-7c3fd1d5 sending SUBSCRIBE (Mid: 1, Topic: a/b/c, QoS: 0, Options: 0x00)
Client nanomq-7c3fd1d5 sending PINGREQ
Client nanomq-7c3fd1d5 sending CONNECT
Client nanomq-7c3fd1d5 received CONNACK (0)
Client nanomq-7c3fd1d5 sending SUBSCRIBE (Mid: 2, Topic: a/b/c, QoS: 0, Options: 0x00)

`$ mosquitto_sub -t a/b/c  -d`

Client (null) sending CONNECT
Client (null) received CONNACK (0)
Client (null) sending SUBSCRIBE (Mid: 1, Topic: a/b/c, QoS: 0, Options: 0x00)
Client (null) received SUBACK
Subscribed (mid: 1): 0

**Comment by wanghaEMQ** [comment]
Hi, this error was fixed by #340. You can go to the repository NanoNNG and see more details

**Comment by lee-emqx** [comment]
thank you @wanghaEMQ
