### ISSUE TITLE
编译时候缺少文件

### ISSUE THREAD

**Issue by kami0314** [nanomq/nanomq#440]
![image](https://user-images.githubusercontent.com/25736811/158743205-3b61196c-7457-4619-bdf0-bdfa2927ebd2.png)
FAILED: nng/CMakeFiles/nng.dir/src/sp/protocol/mqtt/nmq_mqtt.c.o
/usr/bin/cc -DMQ -DNNG_ENABLE_STATS -DNNG_HAVE_ABSTRACT_SOCKETS -DNNG_HAVE_BACKTRACE=1 -DNNG_HAVE_BUS0 -DNNG_HAVE_CLOCK_GETTIME=1 -DNNG_HAVE_EPOLL=1 -DNNG_HAVE_EPOLL_CREATE1=1 -DNNG_HAVE_EVENTFD=1 -DNNG_HAVE_FLOCK=1 -DNNG_HAVE_LIBNSL=1 -DNNG_HAVE_LOCKF=1 -DNNG_HAVE_MQTT_BROKER -DNNG_HAVE_MQTT_CLIENT -DNNG_HAVE_MSG_CONTROL=1 -DNNG_HAVE_PAIR0 -DNNG_HAVE_PAIR1 -DNNG_HAVE_PTHREAD_ATFORK_PTHREAD=1 -DNNG_HAVE_PTHREAD_SETNAME_NP=1 -DNNG_HAVE_PUB0 -DNNG_HAVE_PULL0 -DNNG_HAVE_PUSH0 -DNNG_HAVE_REP0 -DNNG_HAVE_REQ0 -DNNG_HAVE_RESPONDENT0 -DNNG_HAVE_SEMAPHORE_PTHREAD=1 -DNNG_HAVE_SOPEERCRED=1 -DNNG_HAVE_SUB0 -DNNG_HAVE_SURVEYOR0 -DNNG_HAVE_UNIX_SOCKETS=1 -DNNG_HIDDEN_VISIBILITY -DNNG_MAX_TASKQ_THREADS=16 -DNNG_PLATFORM_LINUX -DNNG_PLATFORM_POSIX -DNNG_PRIVATE -DNNG_STATIC_LIB -DNNG_SUPP_HTTP -DNNG_TRANSPORT_INPROC -DNNG_TRANSPORT_IPC -DNNG_TRANSPORT_MQTT_BROKER_TCP -DNNG_TRANSPORT_MQTT_BROKER_WS -DNNG_TRANSPORT_MQTT_TCP -DNNG_TRANSPORT_MQTT_TLS -DNNG_TRANSPORT_TCP -DNNG_TRANSPORT_TLS -DNNG_TRANSPORT_WS -DNNG_USE_EVENTFD -DNOLOG -DSUPP_CLIENT -D_GNU_SOURCE -D_POSIX_PTHREAD_SEMANTICS -D_REENTRANT -D_THREAD_SAFE -I/usr/local/package/nanomq/nng/src -I/usr/local/package/nanomq/nng/include -I/usr/local/package/nanomq/nanolib/include -I/usr/local/package/nanomq/nanomq/include -std=c99 -Wall -Wextra -fno-omit-frame-pointer   -std=gnu99 -MD -MT nng/CMakeFiles/nng.dir/src/sp/protocol/mqtt/nmq_mqtt.c.o -MF nng/CMakeFiles/nng.dir/src/sp/protocol/mqtt/nmq_mqtt.c.o.d -o nng/CMakeFiles/nng.dir/src/sp/protocol/mqtt/nmq_mqtt.c.o -c /usr/local/package/nanomq/nng/src/sp/protocol/mqtt/nmq_mqtt.c
In file included from /usr/local/package/nanomq/nanomq/include/sub_handler.h:7:0,
                 from /usr/local/package/nanomq/nng/src/sp/protocol/mqtt/nmq_mqtt.c:23:
/usr/local/package/nanomq/nanomq/include/broker.h:11:23: 致命错误：stdatomic.h：没有那个文件或目录
 #include <stdatomic.h>
                       ^
编译中断。

**Comment by JaylinYu** [comment]
可以先升级GCC到4.9或以上来完成编译

**Comment by kami0314** [comment]
> 可以先升级GCC到4.9或以上来完成编译

感谢 centos环境下已经解决
