### ISSUE TITLE
Support native build for mobile platforms

### ISSUE THREAD

**Issue by mary-ng5519** [nanomq/nanomq#473]
Folks, please help support Cmake build configurations for mobile platforms, Android, iOS, the use-case is for embeded MQTT broker in mobile apps
Cheers

**Comment by JaylinYu** [comment]
sure, porting to Android is not a big deal, and it is already on my roadmap. As for IOS, this need further investigation.

**Comment by JaylinYu** [comment]
Now NanoMQ can be embedded into mobile apps via JNI/dylib as a .so library
