### ISSUE TITLE
A segmentation fault occurs when a mosquitto client pubs a message

### ISSUE THREAD

**Issue by Hongwei-W** [nanomq/nanomq#67]
A segmentation fault occurs when a mosquitto client tries to pub a message. 

To reproduce this problem, first, launch nanomq broker, the `localhost:1883` was used. Then subscribe to a message using mosquitto_sub before publishing a message with mosquitto_pub. The particular command used is `mosquitto_sub -h "127.0.0.1" -t "abc/123" -d` and `mosquitto_pub -h "127.0.0.1"  -d -t "abc/123" -p 1883 -m "hello"`. The topic of the message could be any type, that is with and without a wildcard character. 

This issue won't be regenerated if a specific client_id is designated for the publisher, for example, no issue will occur when the command `mosquitto_pub -t "abc/123" -m "hello" -h "127.0.0.1" -d -i "abcdefglkfjewjvweionfioewnriejfiewjfwe"`. As for the subscriber, no issue will occur even if no specific client_id is designated. 

By using a debugging function given by VSCode, the exception can be located at the place where the attached screenshot shows. 
<img width="728" alt="Screen Shot 2021-02-26 at 1 42 44 PM" src="https://user-images.githubusercontent.com/56687458/109260116-83393c00-7838-11eb-88b7-1324b3dfbd51.png">

The following is some spec of the running environment:
System: Linux Ubuntu 20x
mosquitto: version 2.0.5
nanomq: commit 2623df67c64eae19f35e25588e2650d723c3cd17, Feb 26 2020 @ 11:42

**Comment by JaylinYu** [comment]
currently, nanomq doesn't support null clientID. Gonna fix it in 0.3.0.
