### ISSUE TITLE
目前支持websocket吗？没看到如何配置websocket端口。

### ISSUE THREAD

**Issue by worldflyingct** [nanomq/nanomq#83]

**Comment by JaylinYu** [comment]
目前不支持，今年优先完成MQTT5.0和nanomsg协议的支持，之后是websocket

**Comment by worldflyingct** [comment]
> 目前不支持，今年优先完成MQTT5.0和nanomsg协议的支持，之后是websocket

鄙人不才，自己写的mqttserver，也是完全非阻塞io，支持websocket，但是我的对协议精简的特别厉害，
密码采用的是关联时间戳的动态密码，主要满足我公司自己使用，希望能相互学习相互进步。  
https://github.com/worldflyingct/mqttserver/tree/master/c

**Comment by JaylinYu** [comment]
多谢您分享开发的broker，已star。最近我在做各类开源MQTT broker的性能测试对比，也会把您的项目一起测试。

**Comment by worldflyingct** [comment]
> 多谢您分享开发的broker，已star。最近我在做各类开源MQTT broker的性能测试对比，也会把您的项目一起测试。

感谢您的信任，我的broker不打算作为全功能的mqtt broker，因为自用，很多特定被砍了，同时添加了根据时间戳与mqttkey动态计算密码的机制，也可以直接发我邮件沟通。

**Comment by gaolaowai** [comment]
Any documentation or example for how to use nanomq for websocket? I see nng library has some code for it.

Thanks!

**Comment by JaylinYu** [comment]
supported
