### ISSUE TITLE
"-DNNG_ENABLE_QUIC" incompatible with  "-DBUILD_SHARED_LIBS=ON" 

### ISSUE THREAD

**Issue by JaylinYu** [nanomq/nanomq#864]
**Describe the bug**
As title said, "-DNNG_ENABLE_QUIC" is incompatible with  "-DBUILD_SHARED_LIBS=ON", these two would cause build fail of NanoMQ

**Expected behavior**
.so requires more work, as we have to move libmosquic.so to a proper folder before entering next compiling stage

THis is just an inform, we will enhance this in short future, for now, plz don't enable  DNNG_ENABLE_QUIC and DBUILD_SHARED_LIBS together.

**Comment by OdyWayne** [comment]
This issue is fixed now.
